create table rep_inv.base_saldos_diarios
(
    id_reg                        bigint generated by default as identity,
    cant_reg                      bigint,
    process_date                  varchar(100),
    client_id                     varchar(100),
    custodian                     varchar(100),
    account_no                    varchar(100),
    cusip                         varchar(100),
    isin                          varchar(100),
    symbol                        varchar(100),
    security_description          varchar(100),
    id_tipo_activo                varchar(100),
    id_sub_tipo_activo            varchar(100),
    id_sub_sub_tipo_activo        varchar(100),
    currency                      varchar(100),
    sum_quantity                  numeric(45, 20),
    sum_market_value              numeric(45, 20),
    sum_usde_market_value         numeric(45, 20),
    sum_comision_devengada_diaria numeric(45, 20),
    constraint base_saldos_diarios_pk
        primary key (id_reg)
);

alter table rep_inv.base_saldos_diarios
    owner to postgres;

