create table rep_inv.rentabilidad_calculada_detallada
(
    nivel                   varchar(100) not null,
    process_date_desde      varchar(100) not null,
    process_date_hasta      varchar(100) not null,
    agregador_n1            varchar(100) not null,
    agregador_n2            varchar(100) not null,
    agregador_n3            varchar(100) not null,
    agregador_n4            varchar(100) not null,
    saldo_dia               numeric(45, 20),
    abonos_dia              numeric(45, 20),
    retiros_dia             numeric(45, 20),
    dividendos_dia          numeric(45, 20),
    saldo_dia_anterior      numeric(45, 20),
    comision_devengada_dia  numeric(45, 20),
    utilidad                numeric(45, 20),
    rentabilidad            numeric(45, 20),
    saldo_rentabilidad      numeric(45, 20),
    suma_saldo_rentabilidad numeric(45, 20),
    suma_saldos_iniciales   numeric(45, 20),
    primer_dia_con_saldo    date,
    ultimo_dia_con_saldo    date,
    dias_con_saldo          integer,
    rentabilidad_ponderada  numeric(45, 20),
    rentabilidad_periodo_cl numeric(45, 20),
    base1_fecha_desde       date,
    base1_fecha_hasta       date,
    base1_rentabilidad      numeric(45, 20),
    base2_fecha_desde       date,
    base2_fecha_hasta       date,
    base2_rentabilidad      numeric(45, 20),
    base3_fecha_desde       date,
    base3_fecha_hasta       date,
    base3_rentabilidad      numeric(45, 20),
    base4_fecha_desde       date,
    base4_fecha_hasta       date,
    base4_rentabilidad      numeric(45, 20),
    base5_fecha_desde       date,
    base5_fecha_hasta       date,
    base5_rentabilidad      numeric(45, 20),
    base6_fecha_desde       date,
    base6_fecha_hasta       date,
    base6_rentabilidad      numeric(45, 20),
    base7_fecha_desde       date,
    base7_fecha_hasta       date,
    base7_rentabilidad      numeric(45, 20),
    base8_fecha_desde       date,
    base8_fecha_hasta       date,
    base8_rentabilidad      numeric(45, 20),
    constraint rentabilidad_calculada_detallada_pk
        primary key (nivel, process_date_desde, process_date_hasta, agregador_n1, agregador_n2, agregador_n3,
                     agregador_n4)
);

alter table rep_inv.rentabilidad_calculada_detallada
    owner to postgres;

