create table rep_inv.rentabilidad_calculada
(
    id                              bigint generated always as identity,
    row_id                          varchar(100) not null,
    nivel                           varchar(100),
    sub_nivel                       bigint,
    process_date                    varchar(100) not null,
    process_date_as_date            date,
    agregador_n1                    varchar(100) not null,
    agregador_n2                    varchar(100) not null,
    agregador_n3                    varchar(100) not null,
    agregador_n4                    varchar(100) not null,
    saldo_dia_anterior              numeric(45, 20),
    abonos_dia                      numeric(45, 20),
    retiros_dia                     numeric(45, 20),
    dividendos_dia                  numeric(45, 20),
    saldo_dia                       numeric(45, 20),
    comision_devengada_dia          numeric(45, 20),
    utilidad                        numeric(45, 20),
    rentabilidad                    numeric(45, 20),
    rentabilidad_base_pitatoria     numeric(45, 20),
    saldo_rentabilidad              numeric(45, 20),
    base1_start_date                date,
    base1_fecha_desde               date,
    base1_fecha_hasta               date,
    base1_rentabilidad              numeric(45, 20),
    base1_dias_con_saldo            integer,
    base1_suma_saldos_iniciales     numeric(45, 20),
    base1_suma_saldo_rentabilidad   numeric(45, 20),
    base1_rentabilidad_ponderada_cl numeric(45, 20),
    base1_rentabilidad_periodo_cl   numeric(45, 20),
    base1_cant_reg                  integer,
    base2_start_date                date,
    base2_fecha_desde               date,
    base2_fecha_hasta               date,
    base2_rentabilidad              numeric(45, 20),
    base2_dias_con_saldo            integer,
    base2_suma_saldos_iniciales     numeric(45, 20),
    base2_suma_saldo_rentabilidad   numeric(45, 20),
    base2_rentabilidad_ponderada_cl numeric(45, 20),
    base2_rentabilidad_periodo_cl   numeric(45, 20),
    base2_cant_reg                  integer,
    base3_start_date                date,
    base3_fecha_desde               date,
    base3_fecha_hasta               date,
    base3_rentabilidad              numeric(45, 20),
    base3_dias_con_saldo            integer,
    base3_suma_saldos_iniciales     numeric(45, 20),
    base3_suma_saldo_rentabilidad   numeric(45, 20),
    base3_rentabilidad_ponderada_cl numeric(45, 20),
    base3_rentabilidad_periodo_cl   numeric(45, 20),
    base3_cant_reg                  integer,
    base4_start_date                date,
    base4_fecha_desde               date,
    base4_fecha_hasta               date,
    base4_rentabilidad              numeric(45, 20),
    base4_dias_con_saldo            integer,
    base4_suma_saldos_iniciales     numeric(45, 20),
    base4_suma_saldo_rentabilidad   numeric(45, 20),
    base4_rentabilidad_ponderada_cl numeric(45, 20),
    base4_rentabilidad_periodo_cl   numeric(45, 20),
    base4_cant_reg                  integer,
    base5_start_date                date,
    base5_fecha_desde               date,
    base5_fecha_hasta               date,
    base5_rentabilidad              numeric(45, 20),
    base5_dias_con_saldo            integer,
    base5_suma_saldos_iniciales     numeric(45, 20),
    base5_suma_saldo_rentabilidad   numeric(45, 20),
    base5_rentabilidad_ponderada_cl numeric(45, 20),
    base5_rentabilidad_periodo_cl   numeric(45, 20),
    base5_cant_reg                  integer,
    base6_start_date                date,
    base6_fecha_desde               date,
    base6_fecha_hasta               date,
    base6_rentabilidad              numeric(45, 20),
    base6_dias_con_saldo            integer,
    base6_suma_saldos_iniciales     numeric(45, 20),
    base6_suma_saldo_rentabilidad   numeric(45, 20),
    base6_rentabilidad_ponderada_cl numeric(45, 20),
    base6_rentabilidad_periodo_cl   numeric(45, 20),
    base6_cant_reg                  integer,
    base7_start_date                date,
    base7_fecha_desde               date,
    base7_fecha_hasta               date,
    base7_rentabilidad              numeric(45, 20),
    base7_dias_con_saldo            integer,
    base7_suma_saldos_iniciales     numeric(45, 20),
    base7_suma_saldo_rentabilidad   numeric(45, 20),
    base7_rentabilidad_ponderada_cl numeric(45, 20),
    base7_rentabilidad_periodo_cl   numeric(45, 20),
    base7_cant_reg                  integer,
    base8_start_date                date,
    base8_fecha_desde               date,
    base8_fecha_hasta               date,
    base8_rentabilidad              numeric(45, 20),
    base8_dias_con_saldo            integer,
    base8_suma_saldos_iniciales     numeric(45, 20),
    base8_suma_saldo_rentabilidad   numeric(45, 20),
    base8_rentabilidad_ponderada_cl numeric(45, 20),
    base8_rentabilidad_periodo_cl   numeric(45, 20),
    base8_cant_reg                  integer,
    constraint rentabilidad_calculada_pk
        primary key (id)
);

alter table rep_inv.rentabilidad_calculada
    owner to postgres;

