create table zz_backup.tbvw_maestro_movimientos_pershing_20241017
(
    custodian                  varchar(100),
    client_id                  varchar(100),
    office_id                  varchar(100),
    account_no                 varchar(100),
    name                       varchar(100),
    process_date               varchar(100),
    tipo_reg                   varchar(100),
    trade_date                 date,
    settlement_date            date,
    activity                   varchar(100),
    buy_sell_code              varchar(100),
    buy_sell_value             varchar(100),
    quantity                   numeric(45, 20),
    price                      numeric(45, 20),
    commission                 numeric(45, 20),
    fees                       numeric(45, 20),
    net_amount                 numeric(45, 20),
    usde_net_amount            numeric(45, 20),
    principal                  numeric(45, 20),
    cusip                      varchar(100),
    symbol                     varchar(100),
    isin                       varchar(100),
    currency                   varchar(100),
    fx_rate                    numeric(45, 20),
    interest                   numeric(45, 20),
    currency_base              varchar(100),
    cash_margin                varchar(100),
    product_type               varchar(100),
    security_description       varchar(100),
    activity_description       varchar(100),
    activity_code              varchar(100),
    source_code                varchar(100),
    description_1              text,
    description_2              text,
    description_3              text,
    ticker                     varchar(100),
    id_sub_sub_tipo            varchar(100),
    id_sub_tipo                varchar(100),
    id_tipo                    varchar(100),
    nombre_sub_sub_tipo        varchar(100),
    flujo_neto                 integer,
    ingreso_egreso             boolean,
    retiro                     numeric(45, 20),
    recaudo                    numeric(45, 20),
    id_cuenta_custodio         varchar(100),
    tipo_identificador_cliente varchar(100)
);

alter table zz_backup.tbvw_maestro_movimientos_pershing_20241017
    owner to postgres;

