create table zz_backup.tbvw_maestro_saldos_pershing_from_ria_20260518
(
    process_date              varchar(100),
    client_id                 varchar(100),
    account_no                varchar(100),
    symbol                    varchar(100),
    cusip                     varchar(100),
    isin_code                 varchar(100),
    quantity                  numeric,
    market_price              numeric(45, 20),
    market_value              numeric(45, 20),
    fx_rate                   numeric(45, 20),
    usde_market_value         numeric(45, 20),
    usde_market_price         numeric(45, 20),
    comision_devengada_diaria numeric(45, 20),
    row_no                    bigint generated by default as identity,
    constraint pk_tbvw_maestro_saldos_pershing_row_no
        primary key (row_no)
);

alter table zz_backup.tbvw_maestro_saldos_pershing_from_ria_20260518
    owner to postgres;

