create table stage_pershing.stage_acct_reg_c
(
    id                               bigint generated always as identity,
    id_proceso                       bigint,
    process_date                     varchar(100),
    transaction_code                 varchar(100),
    record_indicator_value           varchar(100),
    record_id_sequence_number        integer,
    account_number                   varchar(100),
    ibd_number                       varchar(100),
    campo_6                          varchar(100),
    ip_number                        varchar(100),
    account_short_name               varchar(100),
    campo_9                          varchar(100),
    addr_1_trx_code                  varchar(100),
    addr_1_special_handling_ind      varchar(100),
    addr_1_delivery_id               varchar(100),
    addr_1_attention_line_prefix     varchar(100),
    addr_1_attention_line_detail     varchar(100),
    addr_1_line_1                    varchar(100),
    addr_1_line_2                    varchar(100),
    addr_1_line_3                    varchar(100),
    addr_1_line_4                    varchar(100),
    addr_1_city_state                varchar(100),
    addr_1_country_code              varchar(100),
    campo_21                         varchar(100),
    campo_22                         varchar(100),
    campo_23                         varchar(100),
    campo_24                         varchar(100),
    campo_25                         varchar(100),
    campo_26                         varchar(100),
    campo_27                         varchar(100),
    campo_28                         varchar(100),
    campo_29                         varchar(100),
    campo_30                         varchar(100),
    addr_2_trx_code                  varchar(100),
    addr_2_special_handling_ind      varchar(100),
    addr_2_delivery_id               varchar(100),
    addr_2_attention_line_prefix     varchar(100),
    addr_2_attention_line_detail     varchar(100),
    addr_2_line_1                    varchar(100),
    addr_2_line_2                    varchar(100),
    addr_2_line_3                    varchar(100),
    addr_2_line_4                    varchar(100),
    addr_2_city_state                varchar(100),
    addr_2_country_code              varchar(100),
    account_description              varchar(100),
    set_as_mail_addr_2_ind           varchar(100),
    campo_44                         varchar(100),
    principal_billing_allocation_pct numeric(45, 20),
    campo_46                         varchar(100),
    seasonal_addr_id_1               varchar(100),
    from_date_1                      date,
    to_date_1                        date,
    seasonal_addr_id_2               varchar(100),
    from_date_2                      date,
    to_date_2                        date,
    seasonal_addr_id_3               varchar(100),
    from_date_3                      date,
    to_date_3                        date,
    cost_basis_acct_system           varchar(100),
    disposition_method_mutual_funds  varchar(100),
    disposition_method_other         varchar(100),
    disposition_method_stocks        varchar(100),
    campo_60                         varchar(100),
    amortize_taxable_premium_bonds   varchar(100),
    accrue_market_disc_based_on      varchar(100),
    accrue_market_disc_income        varchar(100),
    campo_64                         varchar(100),
    campo_65                         varchar(100),
    campo_66                         varchar(100),
    eor                              varchar(100),
    constraint stage_acct_reg_c_pk
        primary key (id)
);

alter table stage_pershing.stage_acct_reg_c
    owner to postgres;

