create table stage_pershing.stage_gcus_reg_a
(
    id                                     bigint generated always as identity,
    id_proceso                             bigint,
    process_date                           varchar(100),
    transaction_code                       varchar(100),
    record_indicator_value                 varchar(100),
    record_id_sequence_number              integer,
    account_number                         varchar(100),
    cusip_number                           varchar(100),
    portfolio_currency                     varchar(100),
    campo_7                                varchar(100),
    underlying_cusip_number                varchar(100),
    country_code                           varchar(100),
    campo_10                               varchar(100),
    ip_record_number                       varchar(100),
    ibd_number                             varchar(100),
    currency_security_indicator            varchar(100),
    issue_currency                         varchar(100),
    datestamp_trade_date                   date,
    datestamp_settlement_date              date,
    trade_date_quantity                    numeric(45, 20),
    trade_date_quantity_sign               varchar(100),
    settlement_date_quantity               numeric(45, 20),
    settlement_date_quantity_sign          varchar(100),
    seg_quantity                           numeric(45, 20),
    seg_quantity_sign                      varchar(100),
    safekeeping_quantity                   numeric(45, 20),
    safekeeping_sign                       varchar(100),
    transfer_quantity                      numeric(45, 20),
    transfer_quantity_sign                 varchar(100),
    pending_transfer_quantity              numeric(45, 20),
    pending_transfer_quantity_sign         varchar(100),
    legal_transfer_quantity                numeric(45, 20),
    legal_transfer_quantity_sign           varchar(100),
    tendered_quantity                      numeric(45, 20),
    tendered_quantity_sign                 varchar(100),
    pending_papers                         numeric(45, 20),
    pending_papers_sign                    varchar(100),
    short_against_the_box_quantity         numeric(45, 20),
    short_against_the_box_quantity_sign    varchar(100),
    networked_quantity                     numeric(45, 20),
    networked_quantity_sign                varchar(100),
    pending_split_quantity                 numeric(45, 20),
    pending_split_quantity_sign            varchar(100),
    quantity_covering_options              numeric(45, 20),
    quantity_covering_options_sign         varchar(100),
    trade_date_quantity_bought             numeric(45, 20),
    trade_date_quantity_bought_sign        varchar(100),
    trade_date_quantity_sold               numeric(45, 20),
    trade_date_quantity_sold_sign          varchar(100),
    fed_rquirement                         numeric(45, 20),
    fed_rquirement_sign                    varchar(100),
    house_margin_requirement               numeric(45, 20),
    house_margin_requirement_sign          varchar(100),
    nyse_requirement                       numeric(45, 20),
    nyse_requirement_sign                  varchar(100),
    equity_requirment                      numeric(45, 20),
    equity_requirment_sign                 varchar(100),
    security_symbol                        varchar(100),
    security_type                          varchar(100),
    security_mod                           varchar(100),
    security_calc                          varchar(100),
    minor_product_code                     varchar(100),
    network_eligibility_indicator          varchar(100),
    strike_price                           numeric(45, 20),
    strike_price_sign                      varchar(100),
    expiration_maturity_date               date,
    contract_size                          numeric(45, 20),
    conversion_ratio                       numeric(45, 20),
    account_short_name                     varchar(100),
    state_code                             varchar(100),
    country_code_account                   varchar(100),
    campo_69                               varchar(100),
    number_security_description_lines      integer,
    security_description_line_1            varchar(100),
    security_description_line_2            varchar(100),
    security_description_line_3            varchar(100),
    security_description_line_4            varchar(100),
    security_description_line_5            varchar(100),
    security_description_line_6            varchar(100),
    dividend_option                        varchar(100),
    long_term_capital_gains_option         varchar(100),
    short_term_capital_gains_option        varchar(100),
    firm_trading_indicator                 varchar(100),
    position_currency_security             varchar(100),
    trade_date_liquidating_value           numeric(45, 20),
    trade_date_liquidating_value_sign      varchar(100),
    pool_factor                            numeric(45, 20),
    pool_factor_sign                       varchar(100),
    exchange_rate                          numeric(45, 20),
    exchange_rate_sign                     varchar(100),
    settlement_date_liquidating_value      numeric(45, 20),
    settlement_date_liquidating_value_sign varchar(100),
    campo_90                               varchar(100),
    alternate_security_id_type             varchar(100),
    alternate_security_id                  varchar(100),
    campo_93                               varchar(100),
    eor                                    varchar(100),
    constraint stage_gcus_reg_a_pk
        primary key (id)
);

alter table stage_pershing.stage_gcus_reg_a
    owner to postgres;

