create table stage_pershing.stage_gcus_reg_b
(
    id                                                           bigint generated always as identity,
    id_proceso                                                   bigint,
    process_date                                                 varchar(100),
    transaction_code                                             varchar(100),
    record_indicator_value                                       varchar(100),
    recor_id_sequence_number                                     integer,
    account_number                                               varchar(100),
    cusip_number                                                 varchar(100),
    position_currency                                            varchar(100),
    campo_7                                                      varchar(100),
    underlying_cusip_number                                      varchar(100),
    country_code                                                 varchar(100),
    campo_10                                                     varchar(100),
    ip_record_number                                             varchar(100),
    ibd_number                                                   varchar(100),
    fully_paid_lending_quantity                                  numeric(45, 20),
    fully_paid_lending_quantity_sign                             varchar(100),
    fully_paid_lending_quantity_collateral_amount                numeric(45, 20),
    fully_paid_lending_quantity_collateral_amount_sign           varchar(100),
    option_root_id                                               varchar(100),
    expiration_date                                              date,
    call_put_indicator                                           varchar(100),
    strike_price                                                 numeric(45, 20),
    trade_date_repo_quantity                                     numeric(45, 20),
    trade_date_repo_quantity_sign                                varchar(100),
    settlement_date_repo_quantity                                numeric(45, 20),
    settlement_date_repo_quantity_sign                           varchar(100),
    trade_date_reverse_repo_quantity                             numeric(45, 20),
    trade_date_reverse_repo_quantity_sign                        varchar(100),
    settlement_date_reverse_repo_quantity                        numeric(45, 20),
    settlement_date_reverse_repo_quantity_sign                   varchar(100),
    collateral_pledge_quantity                                   numeric(45, 20),
    collateral_pledge_quantity_sign                              varchar(100),
    corporate_exec_serv_collateral_pledge_quantity               numeric(45, 20),
    corporate_exec_serv_collateral_pledge_quantity_sign          varchar(100),
    trade_date_repo_liquidating_value                            numeric(45, 20),
    trade_date_repo_liquidating_value_sign                       varchar(100),
    settlement_date_repo_liquidating_value                       numeric(45, 20),
    settlement_date_repo_liquidating_value_sign                  varchar(100),
    trade_date_reverse_repo_liquidating_value                    numeric(45, 20),
    trade_date_reverse_repo_liquidating_value_sign               varchar(100),
    settlement_date_reverse_repo_liquidating_value               numeric(45, 20),
    settlement_date_reverse_repo_liquidating_value_sign          varchar(100),
    collateral_pledge_liquidating_value                          numeric(45, 20),
    collateral_pledge_liquidating_value_sign                     varchar(100),
    corporate_exec_serv_collateral_pledge_liquidating_value      numeric(45, 20),
    corporate_exec_serv_collateral_pledge_liquidating_value_sign varchar(100),
    trade_date_repo_loan_amount                                  numeric(45, 20),
    trade_date_repo_loan_amount_sign                             varchar(100),
    settlement_date_repo_loan_amount                             numeric(45, 20),
    settlement_date_repo_loan_amount_sign                        varchar(100),
    trade_date_reverse_repo_loan_amount                          numeric(45, 20),
    trade_date_reverse_repo_loan_amount_sign                     varchar(100),
    settlement_date_reverse_repo_loan_amount                     numeric(45, 20),
    settlement_date_reverse_repo_loan_amount_sign                varchar(100),
    accrued_interes_value                                        numeric(45, 20),
    accrued_interes_value_sign                                   varchar(100),
    dividend_or_coupon_rate                                      numeric(45, 20),
    pending_split_quantity_liquidating_value                     numeric(45, 20),
    pending_split_quantity_liquidating_value_sign                varchar(100),
    campo_58                                                     varchar(100),
    internal_non_dollar_symbol                                   varchar(100),
    pledged_quantity                                             numeric(45, 20),
    pledged_quantity_sign                                        varchar(100),
    campo_62                                                     varchar(100),
    eor                                                          varchar(100),
    constraint stage_gcus_reg_b_pk
        primary key (id)
);

alter table stage_pershing.stage_gcus_reg_b
    owner to postgres;

