create table stage_pershing.stage_acct_reg_w
(
    id                               bigint generated always as identity,
    id_proceso                       bigint,
    process_date                     varchar(100),
    transaction_code                 varchar(100),
    record_indicator_value           varchar(100),
    record_id_sequence_number        integer,
    account_number                   varchar(100),
    ibd_number                       varchar(100),
    campo_6                          varchar(100),
    ip_number                        varchar(100),
    account_short_name               varchar(100),
    campo_9                          varchar(100),
    record_transaction_code          varchar(100),
    non_us_dollar_trading            varchar(100),
    base_currency                    varchar(100),
    income_currency                  varchar(100),
    statement_language               varchar(100),
    statement_format_code            varchar(100),
    msrb_statement_ind               varchar(100),
    campo_17                         varchar(100),
    pep                              varchar(100),
    first_name_pep                   varchar(100),
    last_name_pep                    varchar(100),
    suffix_pep                       varchar(100),
    political_office_held            varchar(100),
    country_of_office                varchar(100),
    foreign_bank_account_ind         varchar(100),
    foreign_bank_cert_date           date,
    foreign_bank_cert_exp_date       date,
    central_bank_ind                 varchar(100),
    acct_foreign_financial_inst      varchar(100),
    foreign_bank_acct_oper_1         varchar(100),
    foreign_bank_acct_oper_2         varchar(100),
    foreign_bank_acct_oper_3         varchar(100),
    number_people_own                varchar(100),
    proprietary_acct_owned           varchar(100),
    campo_34                         varchar(100),
    tel_1_transaction_code           varchar(100),
    tel_1_us_ind                     varchar(100),
    tel_1_type_id                    varchar(100),
    tel_1_number                     varchar(100),
    tel_1_extension                  varchar(100),
    tel_2_transaction_code           varchar(100),
    tel_2_us_ind                     varchar(100),
    tel_2_type_id                    varchar(100),
    tel_2_number                     varchar(100),
    tel_2_extension                  varchar(100),
    tel_3_transaction_code           varchar(100),
    tel_3_us_ind                     varchar(100),
    tel_3_type_id                    varchar(100),
    tel_3_number                     varchar(100),
    tel_3_extension                  varchar(100),
    tel_4_transaction_code           varchar(100),
    tel_4_us_ind                     varchar(100),
    tel_4_type_id                    varchar(100),
    tel_4_number                     varchar(100),
    tel_4_extension                  varchar(100),
    tel_5_transaction_code           varchar(100),
    tel_5_us_ind                     varchar(100),
    tel_5_type_id                    varchar(100),
    tel_5_number                     varchar(100),
    tel_5_extension                  varchar(100),
    tel_6_transaction_code           varchar(100),
    tel_6_us_ind                     varchar(100),
    tel_6_type_id                    varchar(100),
    tel_6_number                     varchar(100),
    tel_6_extension                  varchar(100),
    tel_7_transaction_code           varchar(100),
    tel_7_us_ind                     varchar(100),
    tel_7_type_id                    varchar(100),
    tel_7_number                     varchar(100),
    tel_7_extension                  varchar(100),
    tel_8_transaction_code           varchar(100),
    tel_8_us_ind                     varchar(100),
    tel_8_type_id                    varchar(100),
    tel_8_number                     varchar(100),
    tel_8_extension                  varchar(100),
    email_address                    varchar(100),
    external_position_ind            varchar(100),
    purge_eligible_ind               varchar(100),
    advisory_acct_ind                varchar(100),
    product_profile_code             varchar(100),
    cents_per_share_discount         integer,
    campo_81                         varchar(100),
    option_disclosure_date           date,
    campo_83                         varchar(100),
    country_acct_level_tax_residency varchar(100),
    eor                              varchar(100),
    constraint stage_acct_reg_w_pk
        primary key (id)
);

alter table stage_pershing.stage_acct_reg_w
    owner to postgres;

