create table public.authorities
(
    id        bigint generated by default as identity,
    authority varchar(255),
    user_id   bigint,
    primary key (id),
    constraint authorities_ui_user_id_authority
        unique (user_id, authority),
    constraint authorities_ui_user_id
        foreign key (user_id) references public.users
);

alter table public.authorities
    owner to postgres;

