create table public.control_diario
(
    id                  bigint generated by default as identity,
    correlativo_diario  integer   default '-1'::integer not null,
    process_date        varchar(100)                    not null,
    timestamp_control   timestamp                       not null,
    timestamp_registro  timestamp default now()         not null,
    id_control          integer                         not null,
    glosa_control       varchar(1000)                   not null,
    descripcion_control varchar(1000)                   not null,
    identificador       varchar(100)                    not null,
    cant_reg            integer                         not null,
    username            varchar(30)                     not null,
    constraint control_diario_pk
        primary key (id)
            deferrable
);

alter table public.control_diario
    owner to postgres;

