create table public.users
(
    id       bigint generated by default as identity,
    enabled  boolean,
    password varchar(100),
    username varchar(30),
    primary key (id),
    constraint users_ui_username
        unique (username)
);

alter table public.users
    owner to postgres;

