/*
2024-09-13
Actual: 8.3.0-COL
Last:   8.2.0-COL
*/

--========================================================================
--========================================================================
--========================================================================
--Creción de usuarios admin y app
/*
CREATE USER mmii_admindb CREATEDB CREATEROLE PASSWORD 'b55tO<RB4aza';
GRANT azure_pg_admin TO mmii_admindb;
--create database qande_mmii with owner mmii_admindb;
create database qande_mmii;
CREATE USER mmii_appuserdb PASSWORD 'H;859md+5GAf';
GRANT CONNECT ON DATABASE qande_mmii TO mmii_appuserdb;
--ALTER DEFAULT PRIVILEGES FOR ROLE mmii_appuserdb GRANT SELECT, INSERT, DELETE ON TABLES TO mmii_appuserdb;
--ALTER DEFAULT PRIVILEGES FOR ROLE mmii_appuserdb GRANT EXECUTE ON FUNCTIONS TO mmii_appuserdb;
*/

--========================================================================
--========================================================================
--========================================================================
-- Excepciones comerciales comisión

alter table clientes.comision_cuenta
    alter column id type BIGINT using id::BIGINT;

alter table clientes.comision_cuenta
    alter column id
        set generated by default;
alter table clientes.comision_cuenta
    alter column comision_diaria_saldo drop not null;

alter table clientes.comision_cuenta
    alter column comision_diaria_saldo set default NULL;

alter table clientes.comision_cuenta
    add column log_fecha_creacion timestamp NOT NULL default now(),
    add column log_usuario_creacion VARCHAR(100) NOT NULL;



create unique index cuenta_ui_cliente_cuenta
    on clientes.cuenta (id_cliente, id_cuenta_custodio, id_custodio);

CREATE VIEW clientes.vw_maestro_comision AS
    select
        ROW_NUMBER() OVER (ORDER BY com_cta.id) as row_id,
        com_cta.id, com_cta.id_cuenta, com_cta.comision_diaria_saldo, com_cta.fecha_inicio_vigencia, com_cta.log_fecha_creacion, com_cta.log_usuario_creacion,
        vw_cte_cta.id_interno_cliente, vw_cte_cta.identificador_cliente, vw_cte_cta.nombre_cliente, vw_cte_cta.id_tipo_identificador_cliente, vw_cte_cta.tipo_identificador_cliente, vw_cte_cta.glosa_identificador_cliente, vw_cte_cta.id_interno_cuenta, vw_cte_cta.id_custodio, vw_cte_cta.id_cuenta_custodio, vw_cte_cta.habilitado
    from clientes.comision_cuenta com_cta
    INNER JOIN clientes.vw_maestro_clientes_cuentas vw_cte_cta
    ON com_cta.id_cuenta = vw_cte_cta.id_interno_cuenta
    ;


--========================================================================
--========================================================================
--========================================================================
-- ROL nueva opción menú
insert into public.authorities (authority, user_id)
SELECT 'ROLE_OP_MANT_COMIS_CTA' as authority, id as user_id FROM public.users
WHERE username in ('usuario', 'admin-qye', 'user-qye', 'juan.guerra')
;



--========================================================================
--========================================================================
--========================================================================
--




--========================================================================
--========================================================================
--========================================================================
--





--========================================================================
--========================================================================
--========================================================================
--




--========================================================================
--========================================================================
--========================================================================
--


--========================================================================
--========================================================================
--========================================================================
--


--========================================================================
--========================================================================
--========================================================================
--



--========================================================================
--========================================================================
--========================================================================
--


--========================================================================
--========================================================================
--========================================================================
--




--========================================================================
--========================================================================
--========================================================================
--


--========================================================================
--========================================================================
--========================================================================
--



--========================================================================
--========================================================================
--========================================================================
--



