openapi: 3.0.3
info:
  title: API Conexión SW MMII Q&E
  description: |-
    Este es un documento que describe la API para conectividad con el Sistema de MMII.
    
    Este documento puede ser visualizado y editado en el [Editor Swagger](https://editor.swagger.io), además de otras herramientas
  contact:
    email: contacto@qande.cl
  version: 8.0.0
externalDocs:
  description: Acerca de OAS
  url: https://swagger.io/specification/
servers:
  - url: https://mmii-proteccion-dev.qande.cl/core-web-col-web/api
  - url: https://mmii-proteccion.qande.cl/core-web-col-web/api
paths:
  /status:
    get:
      tags:
        - status
      summary: Obtiene el estado de la API
      description: Obtiene el estado de la API
      responses:
        '200':
          description: Mensaje recibido correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseOk'
        '400':
          description: Error en API Key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'
        '500':
          description: Error en la oepración en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'
  /reportes-maestros/{process-date}:
    get:
      tags:
        - archivos
      summary: Obtiene los datos de los Reportes Maestros
      description: Obtiene los datos de los Reportes Maestros para una fecha de proceso dada
      parameters:
        - name: x-api_key
          in: header
          description: 'Api Key necesario para consumir API'
          required: true
          schema:
            type: string
        - name: x-client_id
          in: header
          description: 'ID único de app cliente que consume API'
          required: true
          schema:
            type: string
        - name: process-date
          in: path
          description: 'Fecha de Proceso en formato YYYYMMDD'
          example: 20230528
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReporteMaestrosResponseOk'
        '4XX':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReporteMaestrosResponseError'
        '5XX':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReporteMaestrosResponseError'
      security:
        - api_key: [ ]
  /archivos/reportes-maestros/{process-date}:
    get:
      tags:
        - archivos
      summary: Obtiene archivos Maestros
      description: Obtiene archivos Maestros Cuentas, Saldos y Movimientos para una fecha de proceso dada
      parameters:
        - name: x-api_key
          in: header
          description: 'Api Key necesario para consumir API'
          required: true
          schema:
            type: string
        - name: x-client_id
          in: header
          description: 'ID único de app cliente que consume API'
          required: true
          schema:
            type: string
        - name: process-date
          in: path
          description: 'Fecha de Proceso en formato YYYYMMDD'
          example: 20230528
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArchivosMaestrosResponseOk'
        '4XX':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArchivosMaestrosResponseError'
        '5XX':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArchivosMaestrosResponseError'
      security:
        - api_key: [ ]
  /retornos:
    get:
      tags:
        - retornos
      summary: Devuelve retornos
      description: Devuelve retornos de las cuentas a una fecha o periodo especificado
      parameters:
        - name: x-api_key
          in: header
          description: 'Api Key necesario para consumir API'
          required: true
          schema:
            type: string
        - name: x-client_id
          in: header
          description: 'ID único de app cliente que consume API'
          required: true
          schema:
            type: string
        - name: periodo
          in: path
          description: 'Periodo a consultar en formato YYYYMM'
          example: 202505
          required: true
          schema:
            type: integer
        - name: dia
          in: path
          description: 'Día del periodo a consultar. Si es 0, se usa el último día del periodo (cierre de mes)'
          example: 2
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetornosResponseOk'
        '4XX':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetornosResponseError'
        '5XX':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetornosResponseError'
      security:
        - api_key: [ ]
components:
  schemas:
    ArchivosMaestrosResponseOk:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        lista-archivos:
          $ref: '#/components/schemas/ListaArchivos'
    ArchivosMaestrosResponseError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    ReporteMaestrosResponseOk:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        maestro-movimientos:
          $ref: '#/components/schemas/ListaMovimientoCustodio'
        maestro-saldos:
          $ref: '#/components/schemas/ListaSaldoCustodio'
    ReporteMaestrosResponseError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    RetornosResponseOk:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        lista-retornos:
          $ref: '#/components/schemas/ListaRetornos'
    RetornosResponseError:
      $ref: '#/components/schemas/ApiResponseError'
    ApiResponseOk:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    ApiResponseError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    SaldoCustodio:
      type: object
      properties:
        custodian:
          type: string
        office-id:
          type: string
        client-id:
          type: string
        tipo-id:
          type: string
        account-no:
          type: string
        name:
          type: string
        process-date:
          type: string
        cusip:
          type: string
        security-description:
          type: string
        quantity:
          type: number
          format: float
        mkt-price:
          type: number
          format: float
        currency:
          type: string
        mkt-value:
          type: number
          format: float
        fx-rate:
          type: number
          format: float
        usde-mkt-value:
          type: number
          format: float
        usde-mkt-price:
          type: number
          format: float
        nombre-sub-sub-tipo:
          type: string
        fee-anual:
          type: number
          format: float
        fee-proteccion:
          type: number
          format: float
        fee-proteccion-diario:
          type: number
          format: float
        ingreso-proteccion:
          type: number
          format: float
    ListaSaldoCustodio:
      type: array
      items:
        $ref: '#/components/schemas/SaldoCustodio'
    MovimientoCustodio:
      type: object
      properties:
        custodian:
          type: string
        client-id:
          type: string
        tipo-id:
          type: string
        office-id:
          type: string
        account-no:
          type: string
        name:
          type: string
        process-date:
          type: string
        trade-date:
          type: string
        settl-date:
          type: string
        activity:
          type: string
        buy-sell:
          type: string
        quantity:
          type: number
          format: float
        price:
          type: number
          format: float
        comission:
          type: number
          format: float
        fees:
          type: number
          format: float
        net-amount:
          type: number
          format: float
        usde-net-amount:
          type: number
          format: float
        principal:
          type: number
          format: float
        cusip:
          type: string
        currency:
          type: string
        fx-rate:
          type: number
          format: float
        cash-margin:
          type: string
        product-type:
          type: string
        security-description:
          type: string
        activity-description:
          type: string
        source-code:
          type: string
        nombre-sub-sub-tipo:
          type: string
        ingreso-egreso-producto:
          type: boolean
        retiro:
          type: number
          format: float
        recaudo:
          type: number
          format: float
    ListaMovimientoCustodio:
      type: array
      items:
        $ref: '#/components/schemas/MovimientoCustodio'
    Archivo:
      type: object
      properties:
        nombre-original:
          description: Nombre original (o referencial) del archivo en el Sistema. No tiene porque ser el mismo nombre con el que se almacena en el Cliente.
          type: string
          example: ArchivoPrueba.csv
        extension:
          description: Extensión del archivo (puede ser vacía).
          type: string
          example: csv
        archivo-base64:
          description: Archivo codificado en base 64. Note que es un string largo, en el ejemplo se ha recortado con ... (3 puntos).
          type: string
          example: UEsDBBQACAgIAKmtq1YAAAAAAAAAAAAAAAALAAAAX3JlbHMvLnJl...EPAAAAAA==
    ListaArchivos:
      type: array
      items:
        $ref: '#/components/schemas/Archivo'
    RetornoCuenta:
      type: object
      properties:
        account-no:
          type: string
        rent-dia:
          type: number
          format: float
        rent-1m:
          type: number
          format: float
        rent-3m:
          type: number
          format: float
        rent-12m:
          type: number
          format: float
        rent-ytd:
          type: number
          format: float
        rent-inicio:
          type: number
          format: float
    ListaRetornos:
      type: array
      items:
        $ref: '#/components/schemas/RetornoCuenta'
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api_key
      in: header