create or replace view pershing.vw_maestro_cuenta
            (id_custodian, custodian, id, ibd_number, id_office, ip_number, account_number, id_proceso, process_date,
             record_id_sequence_number, account_short_name, full_name, full_address, transaction_type,
             autotitled_usertitled_account, account_type_code, registration_type, registration_type_value,
             number_of_account_title_lines, account_registration_line_1, account_registration_line_2,
             account_registration_line_3, account_registration_line_4, account_registration_line_5,
             account_registration_line_6, registration_type_detail, date_account_opened,
             date_account_information_updated, account_status_indicator, pending_closed_date, date_account_closed,
             closing_notice_date, account_reactivated_date, date_account_reopened, proceeds, transfer_instructions,
             income_isntructions, number_of_confirms_for_thi_account, number_of_statements_for_this_account,
             investment_objetive_trans_code, comments_act, employer_shotname, employers_cusip, employers_symbol,
             margin_privileges_revoked, statement_review_date, margin_papers_on_file, cash_margin_account,
             option_papers_on_file, good_faith_margin, ip_discretion_granted, invest_advisor_discretion_granted,
             invest_advisor_discretion_granted_value, third_party_discretion_granted, third_party_name,
             risk_factor_code, investment_objetive_code, option_equities, option_index, option_debt, option_currency,
             option_level_1, option_level_2, option_level_3, option_level_4, option_call_limits, option_put_limits,
             option_total_limits_of_puts_and_calls, non_us_dollar_trading, non_customer_indicator,
             third_party_fee_indicator, third_party_fee_approval_date, intermediary_account_ind, commission_schedule,
             group_index, money_manager_id, money_manager_objective_id, dtc_id_confirm_number, caps_master_mnemonic,
             employee_id, prime_broker_free_fund_indicator, fee_based_account_indicator, fee_based_termination_date,
             plan_name, self_directed_401_k_account_type, plan_type, plan_number, employee_or_employee_relative,
             commission_percent_discount, ind_12_b_1_fee_blocking, name_of_ip_signed_new_account_form,
             date_of_ip_signed_new_account_form, name_of_principal_signed_new_account_form,
             date_of_principal_signed_new_account_form, politically_exposed_person, private_banking_account,
             foreign_bank_account, initial_source_of_funds, usa_patriot_act_exempt_reason, country_of_citizenship_code,
             country_of_citizenship_value, country_of_residence_code, country_of_residence_value, birth_date,
             age_based_fund_roll_exempt, money_fundreform_retail, trusted_contact_status,
             regulatory_account_type_category, account_managed_by_trust_comp_id, voting_auth, customer_type,
             fulfillment_method, credit_interest_indicator, ama_indicator, ama_indicator_value, tax_id_type,
             tax_id_number, date_tax_id_applied_for, w_8_w_9_indicator, w_8_w_9_date_signed, w_8_w_9_effective_date,
             w_8_w_9_document_type, w_8_date_signed, w_8_effective_date, w_9_date_signed, w_9_effective_date,
             tax_status, b_notice_reason_code, first_b_notice_status, date_first_b_notice_status_issued_enforced,
             date_first_notice_status_satisfied, second_b_notice_status, date_second_b_notice_status_issued_enforced,
             date_second_b_notice_status_satisfied, c_notice_status, date_c_notice_status_issued_enforced,
             date_c_notice_status_satisfied, old_account_number, original_account_open_date,
             unidentified_large_trader_id, large_trader_type_code, large_trader_type_last_change_date,
             initial_source_of_funds_other, finance_away, account_funding_date, statement_currency_code,
             future_statement_currency_code, future_statement_currency_code_effective_date,
             account_level_routing_code_1, account_level_routing_code_2, account_level_routing_code_3,
             account_level_routing_code_4, self_directed_ind, digital_advice_ind, pte_account_ind, first_ip, second_ip,
             third_ip, fourth_ip, fifth_ip, sixth_ip, seventh_ip, eighth_ip, ninth_ip, tenth_ip, alert_im_acornym,
             alert_im_access_code, broker_acronym, cross_reference_indicator, bny_trust_indicator,
             source_of_asset_at_acct_opening, commission_doscount_code, external_account_number,
             confirmation_suppression_indicator, date_last_mail_sent, date_last_mail_sent_outside,
             fully_paid_lending_agreement_indicator, fully_paid_lending_agreement_date, custodian_account_type,
             mifid_customer_categorization, cash_management_tran_code, sweep_status_indicator, date_sweep_activated,
             date_sweep_details_changed, cober_margin_debit_indicator, first_fund_sweep_account_id,
             firstfund_sweep_account_percent, first_fundsweep_account_redemption_priority, second_fund_sweep_account_id,
             second_fund_sweep_account_percent, second_fundsweep_account_redemption_priority, type_of_bank_account,
             banklink_aba_number, banklink_dda_number, fund_bank_indicator, w_9_corp_tax_classification_code,
             combined_margin_acct_indicator, pledge_collateral_account_indicator, finra_institutional_account_code,
             proposed_account_reference_id, advisor_model_id, firm_model_style_id, dvp_restriction_code,
             dvp_restriction_exp_date, escheatment_withholding_ind, source_of_origination, source_of_persona,
             client_onboarding_method, tax_filing_code, nor_purpose_collateral_acct_ind, addr_1_trx_code,
             addr_1_special_handling_ind, addr_1_delivery_id, addr_1_attention_line_prefix,
             addr_1_attention_line_detail, addr_1_line_1, addr_1_line_2, addr_1_line_3, addr_1_line_4,
             addr_1_city_state, addr_1_country_code, addr_2_trx_code, addr_2_special_handling_ind, addr_2_delivery_id,
             addr_2_attention_line_prefix, addr_2_attention_line_detail, addr_2_line_1, addr_2_line_2, addr_2_line_3,
             addr_2_line_4, addr_2_city_state, addr_2_country_code, account_description, set_as_mail_addr_2_ind,
             principal_billing_allocation_pct, seasonal_addr_id_1, from_date_1, to_date_1, seasonal_addr_id_2,
             from_date_2, to_date_2, seasonal_addr_id_3, from_date_3, to_date_3, cost_basis_acct_system,
             disposition_method_mutual_funds, disposition_method_other, disposition_method_stocks,
             amortize_taxable_premium_bonds, accrue_market_disc_based_on, accrue_market_disc_income, addr_3_trx_code,
             addr_3_special_handling_ind, addr_3_delivery_id, addr_3_attention_line_prefix,
             addr_3_attention_line_detail, addr_3_line_1, addr_3_line_2, addr_3_line_3, addr_3_line_4,
             addr_3_city_state, addr_3_country_code, set_as_mail_addr_3_ind, addr_4_trx_code,
             addr_4_special_handling_ind, addr_4_delivery_id, addr_4_attention_line_prefix,
             addr_4_attention_line_detail, addr_4_line_1, addr_4_line_2, addr_4_line_3, addr_4_line_4,
             addr_4_city_state, addr_4_country_code, set_as_mail_addr_4_ind, addr_5_trx_code,
             addr_5_special_handling_ind, addr_5_delivery_id, addr_5_attention_line_prefix,
             addr_5_attention_line_detail, addr_5_line_1, addr_5_line_2, addr_5_line_3, addr_5_line_4,
             addr_5_city_state, addr_5_country_code, set_as_mail_addr_5_ind, addr_6_trx_code,
             addr_6_special_handling_ind, addr_6_delivery_id, addr_6_attention_line_prefix,
             addr_6_attention_line_detail, addr_6_line_1, addr_6_line_2, addr_6_line_3, addr_6_line_4,
             addr_6_city_state, addr_6_country_code, set_as_mail_addr_6_ind, addr_7_trx_code,
             addr_7_special_handling_ind, addr_7_delivery_id, addr_7_attention_line_prefix,
             addr_7_attention_line_detail, addr_7_line_1, addr_7_line_2, addr_7_line_3, addr_7_line_4,
             addr_7_city_state, addr_7_country_code, set_as_mail_addr_7_ind, record_transaction_code, base_currency,
             income_currency, statement_language, statement_format_code, msrb_statement_ind, pep, first_name_pep,
             last_name_pep, suffix_pep, political_office_held, country_of_office, foreign_bank_account_ind,
             foreign_bank_cert_date, foreign_bank_cert_exp_date, central_bank_ind, acct_foreign_financial_inst,
             foreign_bank_acct_oper_1, foreign_bank_acct_oper_2, foreign_bank_acct_oper_3, number_people_own,
             proprietary_acct_owned, tel_1_transaction_code, tel_1_us_ind, tel_1_type_id, tel_1_number, tel_1_extension,
             tel_2_transaction_code, tel_2_us_ind, tel_2_type_id, tel_2_number, tel_2_extension, tel_3_transaction_code,
             tel_3_us_ind, tel_3_type_id, tel_3_number, tel_3_extension, tel_4_transaction_code, tel_4_us_ind,
             tel_4_type_id, tel_4_number, tel_4_extension, tel_5_transaction_code, tel_5_us_ind, tel_5_type_id,
             tel_5_number, tel_5_extension, tel_6_transaction_code, tel_6_us_ind, tel_6_type_id, tel_6_number,
             tel_6_extension, tel_7_transaction_code, tel_7_us_ind, tel_7_type_id, tel_7_number, tel_7_extension,
             tel_8_transaction_code, tel_8_us_ind, tel_8_type_id, tel_8_number, tel_8_extension, email_address,
             external_position_ind, purge_eligible_ind, advisory_acct_ind, product_profile_code,
             cents_per_share_discount, option_disclosure_date, country_acct_level_tax_residency)
as
SELECT 'pershing'::character varying(100)                                                         AS id_custodian,
       fn_obtiene_valor_parametro('custodian'::character varying,
                                  'pershing'::character varying)::character varying(100)          AS custodian,
       vw_act.id,
       vw_act.ibd_number,
       "left"(vw_act.account_number::text, 3)                                                     AS id_office,
       vw_act.ip_number,
       vw_act.account_number,
       vw_act.id_proceso,
       vw_act.process_date,
       vw_act.record_id_sequence_number,
       vw_act.account_short_name,
       CASE
           WHEN vw_act.number_of_account_title_lines::text = '1'::text
               THEN TRIM(BOTH FROM vw_act.account_registration_line_1)
           WHEN vw_act.number_of_account_title_lines::text = '2'::text THEN
               (TRIM(BOTH FROM vw_act.account_registration_line_1) || ' '::text) ||
               TRIM(BOTH FROM vw_act.account_registration_line_2)
           WHEN vw_act.number_of_account_title_lines::text = '3'::text THEN
               (((TRIM(BOTH FROM vw_act.account_registration_line_1) || ' '::text) ||
                 TRIM(BOTH FROM vw_act.account_registration_line_2)) || ' '::text) ||
               TRIM(BOTH FROM vw_act.account_registration_line_3)
           WHEN vw_act.number_of_account_title_lines::text = '4'::text THEN
               (((((TRIM(BOTH FROM vw_act.account_registration_line_1) || ' '::text) ||
                   TRIM(BOTH FROM vw_act.account_registration_line_2)) || ' '::text) ||
                 TRIM(BOTH FROM vw_act.account_registration_line_3)) || ' '::text) ||
               TRIM(BOTH FROM vw_act.account_registration_line_4)
           WHEN vw_act.number_of_account_title_lines::text = '5'::text THEN
               (((((((TRIM(BOTH FROM vw_act.account_registration_line_1) || ' '::text) ||
                     TRIM(BOTH FROM vw_act.account_registration_line_2)) || ' '::text) ||
                   TRIM(BOTH FROM vw_act.account_registration_line_3)) || ' '::text) ||
                 TRIM(BOTH FROM vw_act.account_registration_line_4)) || ' '::text) ||
               TRIM(BOTH FROM vw_act.account_registration_line_5)
           WHEN vw_act.number_of_account_title_lines::text = '6'::text THEN
               (((((((((TRIM(BOTH FROM vw_act.account_registration_line_1) || ' '::text) ||
                       TRIM(BOTH FROM vw_act.account_registration_line_2)) || ' '::text) ||
                     TRIM(BOTH FROM vw_act.account_registration_line_3)) || ' '::text) ||
                   TRIM(BOTH FROM vw_act.account_registration_line_4)) || ' '::text) ||
                 TRIM(BOTH FROM vw_act.account_registration_line_5)) || ' '::text) ||
               TRIM(BOTH FROM vw_act.account_registration_line_6)
           ELSE NULL::text
           END::character varying(100)                                                            AS full_name,
       CASE
           WHEN vw_act.number_of_account_title_lines::text = '5'::text
               THEN TRIM(BOTH FROM vw_act.account_registration_line_6)
           WHEN vw_act.number_of_account_title_lines::text = '4'::text THEN
               (TRIM(BOTH FROM vw_act.account_registration_line_5) || ' '::text) ||
               TRIM(BOTH FROM vw_act.account_registration_line_6)
           WHEN vw_act.number_of_account_title_lines::text = '3'::text THEN
               (((TRIM(BOTH FROM vw_act.account_registration_line_4) || ' '::text) ||
                 TRIM(BOTH FROM vw_act.account_registration_line_5)) || ' '::text) ||
               TRIM(BOTH FROM vw_act.account_registration_line_6)
           WHEN vw_act.number_of_account_title_lines::text = '2'::text THEN
               (((((TRIM(BOTH FROM vw_act.account_registration_line_3) || ' '::text) ||
                   TRIM(BOTH FROM vw_act.account_registration_line_4)) || ' '::text) ||
                 TRIM(BOTH FROM vw_act.account_registration_line_5)) || ' '::text) ||
               TRIM(BOTH FROM vw_act.account_registration_line_6)
           WHEN vw_act.number_of_account_title_lines::text = '1'::text THEN
               (((((((TRIM(BOTH FROM vw_act.account_registration_line_2) || ' '::text) ||
                     TRIM(BOTH FROM vw_act.account_registration_line_3)) || ' '::text) ||
                   TRIM(BOTH FROM vw_act.account_registration_line_4)) || ' '::text) ||
                 TRIM(BOTH FROM vw_act.account_registration_line_5)) || ' '::text) ||
               TRIM(BOTH FROM vw_act.account_registration_line_6)
           ELSE NULL::text
           END::character varying(100)                                                            AS full_address,
       vw_act.transaction_type,
       vw_act.autotitled_usertitled_account,
       vw_act.account_type_code,
       vw_act.registration_type,
       par_reg_type.glosa                                                                         AS registration_type_value,
       vw_act.number_of_account_title_lines,
       vw_act.account_registration_line_1,
       vw_act.account_registration_line_2,
       vw_act.account_registration_line_3,
       vw_act.account_registration_line_4,
       vw_act.account_registration_line_5,
       vw_act.account_registration_line_6,
       vw_act.registration_type_detail,
       vw_act.date_account_opened,
       vw_act.date_account_information_updated,
       vw_act.account_status_indicator,
       vw_act.pending_closed_date,
       vw_act.date_account_closed,
       vw_act.closing_notice_date,
       vw_act.account_reactivated_date,
       vw_act.date_account_reopened,
       vw_act.proceeds,
       vw_act.transfer_instructions,
       vw_act.income_isntructions,
       vw_act.number_of_confirms_for_thi_account,
       vw_act.number_of_statements_for_this_account,
       vw_act.investment_objetive_trans_code,
       vw_act.comments_act,
       vw_act.employer_shotname,
       vw_act.employers_cusip,
       vw_act.employers_symbol,
       vw_act.margin_privileges_revoked,
       vw_act.statement_review_date,
       vw_act.margin_papers_on_file,
       CASE
           WHEN vw_act.margin_papers_on_file::text = 'Y'::text THEN 'MARGIN'::text
           ELSE 'CASH'::text
           END::character varying(100)                                                            AS cash_margin_account,
       vw_act.option_papers_on_file,
       vw_act.good_faith_margin,
       vw_act.ip_discretion_granted,
       vw_act.invest_advisor_discretion_granted,
       pershing.fn_obtiene_valor_param_generic_pershing('invest_adv_discr_granted'::character varying,
                                                        vw_act.invest_advisor_discretion_granted) AS invest_advisor_discretion_granted_value,
       vw_act.third_party_discretion_granted,
       vw_act.third_party_name,
       vw_act.risk_factor_code,
       vw_act.investment_objetive_code,
       vw_act.option_equities,
       vw_act.option_index,
       vw_act.option_debt,
       vw_act.option_currency,
       vw_act.option_level_1,
       vw_act.option_level_2,
       vw_act.option_level_3,
       vw_act.option_level_4,
       vw_act.option_call_limits,
       vw_act.option_put_limits,
       vw_act.option_total_limits_of_puts_and_calls,
       vw_act.non_us_dollar_trading,
       vw_act.non_customer_indicator,
       vw_act.third_party_fee_indicator,
       vw_act.third_party_fee_approval_date,
       vw_act.intermediary_account_ind,
       vw_act.commission_schedule,
       vw_act.group_index,
       vw_act.money_manager_id,
       vw_act.money_manager_objective_id,
       vw_act.dtc_id_confirm_number,
       vw_act.caps_master_mnemonic,
       vw_act.employee_id,
       vw_act.prime_broker_free_fund_indicator,
       vw_act.fee_based_account_indicator,
       vw_act.fee_based_termination_date,
       vw_act.plan_name,
       vw_act.self_directed_401_k_account_type,
       vw_act.plan_type,
       vw_act.plan_number,
       vw_act.employee_or_employee_relative,
       vw_act.commission_percent_discount,
       vw_act.ind_12_b_1_fee_blocking,
       vw_act.name_of_ip_signed_new_account_form,
       vw_act.date_of_ip_signed_new_account_form,
       vw_act.name_of_principal_signed_new_account_form,
       vw_act.date_of_principal_signed_new_account_form,
       vw_act.politically_exposed_person,
       vw_act.private_banking_account,
       vw_act.foreign_bank_account,
       vw_act.initial_source_of_funds,
       vw_act.usa_patriot_act_exempt_reason,
       vw_act.primary_country_of_citizenship                                                      AS country_of_citizenship_code,
       par_cc_cit.glosa                                                                           AS country_of_citizenship_value,
       vw_act.country_of_residence                                                                AS country_of_residence_code,
       par_cc_res.glosa                                                                           AS country_of_residence_value,
       vw_act.birth_date,
       vw_act.age_based_fund_roll_exempt,
       vw_act.money_fundreform_retail,
       vw_act.trusted_contact_status,
       vw_act.regulatory_account_type_category,
       vw_act.account_managed_by_trust_comp_id,
       vw_act.voting_auth,
       vw_act.customer_type,
       vw_act.fulfillment_method,
       vw_act.credit_interest_indicator,
       vw_act.ama_indicator,
       CASE
           WHEN vw_act.ama_indicator::text = ANY
                (ARRAY ['1'::character varying::text, '2'::character varying::text, '4'::character varying::text])
               THEN 'C'::text
           ELSE ''::text
           END                                                                                    AS ama_indicator_value,
       vw_act.tax_id_type,
       vw_act.tax_id_number,
       vw_act.date_tax_id_applied_for,
       vw_act.w_8_w_9_indicator,
       vw_act.w_8_w_9_date_signed,
       vw_act.w_8_w_9_effective_date,
       vw_act.w_8_w_9_document_type,
       CASE
           WHEN TRIM(BOTH FROM vw_act.w_8_w_9_indicator) = 'W8'::text THEN vw_act.w_8_w_9_date_signed
           ELSE NULL::date
           END                                                                                    AS w_8_date_signed,
       CASE
           WHEN TRIM(BOTH FROM vw_act.w_8_w_9_indicator) = 'W8'::text THEN vw_act.w_8_w_9_effective_date
           ELSE NULL::date
           END                                                                                    AS w_8_effective_date,
       CASE
           WHEN TRIM(BOTH FROM vw_act.w_8_w_9_indicator) = 'W9'::text THEN vw_act.w_8_w_9_date_signed
           ELSE NULL::date
           END                                                                                    AS w_9_date_signed,
       CASE
           WHEN TRIM(BOTH FROM vw_act.w_8_w_9_indicator) = 'W9'::text THEN vw_act.w_8_w_9_effective_date
           ELSE NULL::date
           END                                                                                    AS w_9_effective_date,
       vw_act.tax_status,
       vw_act.b_notice_reason_code,
       vw_act.first_b_notice_status,
       vw_act.date_first_b_notice_status_issued_enforced,
       vw_act.date_first_notice_status_satisfied,
       vw_act.second_b_notice_status,
       vw_act.date_second_b_notice_status_issued_enforced,
       vw_act.date_second_b_notice_status_satisfied,
       vw_act.c_notice_status,
       vw_act.date_c_notice_status_issued_enforced,
       vw_act.date_c_notice_status_satisfied,
       vw_act.old_account_number,
       vw_act.original_account_open_date,
       vw_act.unidentified_large_trader_id,
       vw_act.large_trader_type_code,
       vw_act.large_trader_type_last_change_date,
       vw_act.initial_source_of_funds_other,
       vw_act.finance_away,
       vw_act.account_funding_date,
       vw_act.statement_currency_code,
       vw_act.future_statement_currency_code,
       vw_act.future_statement_currency_code_effective_date,
       vw_act.account_level_routing_code_1,
       vw_act.account_level_routing_code_2,
       vw_act.account_level_routing_code_3,
       vw_act.account_level_routing_code_4,
       vw_act.self_directed_ind,
       vw_act.digital_advice_ind,
       vw_act.pte_account_ind,
       vw_act.first_ip,
       vw_act.second_ip,
       vw_act.third_ip,
       vw_act.fourth_ip,
       vw_act.fifth_ip,
       vw_act.sixth_ip,
       vw_act.seventh_ip,
       vw_act.eighth_ip,
       vw_act.ninth_ip,
       vw_act.tenth_ip,
       vw_act.alert_im_acornym,
       vw_act.alert_im_access_code,
       vw_act.broker_acronym,
       vw_act.cross_reference_indicator,
       vw_act.bny_trust_indicator,
       vw_act.source_of_asset_at_acct_opening,
       vw_act.commission_doscount_code,
       vw_act.external_account_number,
       vw_act.confirmation_suppression_indicator,
       vw_act.date_last_mail_sent,
       vw_act.date_last_mail_sent_outside,
       vw_act.fully_paid_lending_agreement_indicator,
       vw_act.fully_paid_lending_agreement_date,
       vw_act.custodian_account_type,
       vw_act.mifid_customer_categorization,
       vw_act.cash_management_tran_code,
       vw_act.sweep_status_indicator,
       vw_act.date_sweep_activated,
       vw_act.date_sweep_details_changed,
       vw_act.cober_margin_debit_indicator,
       vw_act.first_fund_sweep_account_id,
       vw_act.firstfund_sweep_account_percent,
       vw_act.first_fundsweep_account_redemption_priority,
       vw_act.second_fund_sweep_account_id,
       vw_act.second_fund_sweep_account_percent,
       vw_act.second_fundsweep_account_redemption_priority,
       vw_act.type_of_bank_account,
       vw_act.banklink_aba_number,
       vw_act.banklink_dda_number,
       vw_act.fund_bank_indicator,
       vw_act.w_9_corp_tax_classification_code,
       vw_act.combined_margin_acct_indicator,
       vw_act.pledge_collateral_account_indicator,
       vw_act.finra_institutional_account_code,
       vw_act.proposed_account_reference_id,
       vw_act.advisor_model_id,
       vw_act.firm_model_style_id,
       vw_act.dvp_restriction_code,
       vw_act.dvp_restriction_exp_date,
       vw_act.escheatment_withholding_ind,
       vw_act.source_of_origination,
       vw_act.source_of_persona,
       vw_act.client_onboarding_method,
       vw_act.tax_filing_code,
       vw_act.nor_purpose_collateral_acct_ind,
       vw_act.addr_1_trx_code,
       vw_act.addr_1_special_handling_ind,
       vw_act.addr_1_delivery_id,
       vw_act.addr_1_attention_line_prefix,
       vw_act.addr_1_attention_line_detail,
       vw_act.addr_1_line_1,
       vw_act.addr_1_line_2,
       vw_act.addr_1_line_3,
       vw_act.addr_1_line_4,
       vw_act.addr_1_city_state,
       vw_act.addr_1_country_code,
       vw_act.addr_2_trx_code,
       vw_act.addr_2_special_handling_ind,
       vw_act.addr_2_delivery_id,
       vw_act.addr_2_attention_line_prefix,
       vw_act.addr_2_attention_line_detail,
       vw_act.addr_2_line_1,
       vw_act.addr_2_line_2,
       vw_act.addr_2_line_3,
       vw_act.addr_2_line_4,
       vw_act.addr_2_city_state,
       vw_act.addr_2_country_code,
       vw_act.account_description,
       vw_act.set_as_mail_addr_2_ind,
       vw_act.principal_billing_allocation_pct,
       vw_act.seasonal_addr_id_1,
       vw_act.from_date_1,
       vw_act.to_date_1,
       vw_act.seasonal_addr_id_2,
       vw_act.from_date_2,
       vw_act.to_date_2,
       vw_act.seasonal_addr_id_3,
       vw_act.from_date_3,
       vw_act.to_date_3,
       vw_act.cost_basis_acct_system,
       vw_act.disposition_method_mutual_funds,
       vw_act.disposition_method_other,
       vw_act.disposition_method_stocks,
       vw_act.amortize_taxable_premium_bonds,
       vw_act.accrue_market_disc_based_on,
       vw_act.accrue_market_disc_income,
       vw_act.addr_3_trx_code,
       vw_act.addr_3_special_handling_ind,
       vw_act.addr_3_delivery_id,
       vw_act.addr_3_attention_line_prefix,
       vw_act.addr_3_attention_line_detail,
       vw_act.addr_3_line_1,
       vw_act.addr_3_line_2,
       vw_act.addr_3_line_3,
       vw_act.addr_3_line_4,
       vw_act.addr_3_city_state,
       vw_act.addr_3_country_code,
       vw_act.set_as_mail_addr_3_ind,
       vw_act.addr_4_trx_code,
       vw_act.addr_4_special_handling_ind,
       vw_act.addr_4_delivery_id,
       vw_act.addr_4_attention_line_prefix,
       vw_act.addr_4_attention_line_detail,
       vw_act.addr_4_line_1,
       vw_act.addr_4_line_2,
       vw_act.addr_4_line_3,
       vw_act.addr_4_line_4,
       vw_act.addr_4_city_state,
       vw_act.addr_4_country_code,
       vw_act.set_as_mail_addr_4_ind,
       vw_act.addr_5_trx_code,
       vw_act.addr_5_special_handling_ind,
       vw_act.addr_5_delivery_id,
       vw_act.addr_5_attention_line_prefix,
       vw_act.addr_5_attention_line_detail,
       vw_act.addr_5_line_1,
       vw_act.addr_5_line_2,
       vw_act.addr_5_line_3,
       vw_act.addr_5_line_4,
       vw_act.addr_5_city_state,
       vw_act.addr_5_country_code,
       vw_act.set_as_mail_addr_5_ind,
       vw_act.addr_6_trx_code,
       vw_act.addr_6_special_handling_ind,
       vw_act.addr_6_delivery_id,
       vw_act.addr_6_attention_line_prefix,
       vw_act.addr_6_attention_line_detail,
       vw_act.addr_6_line_1,
       vw_act.addr_6_line_2,
       vw_act.addr_6_line_3,
       vw_act.addr_6_line_4,
       vw_act.addr_6_city_state,
       vw_act.addr_6_country_code,
       vw_act.set_as_mail_addr_6_ind,
       vw_act.addr_7_trx_code,
       vw_act.addr_7_special_handling_ind,
       vw_act.addr_7_delivery_id,
       vw_act.addr_7_attention_line_prefix,
       vw_act.addr_7_attention_line_detail,
       vw_act.addr_7_line_1,
       vw_act.addr_7_line_2,
       vw_act.addr_7_line_3,
       vw_act.addr_7_line_4,
       vw_act.addr_7_city_state,
       vw_act.addr_7_country_code,
       vw_act.set_as_mail_addr_7_ind,
       vw_act.record_transaction_code,
       vw_act.base_currency,
       vw_act.income_currency,
       vw_act.statement_language,
       vw_act.statement_format_code,
       vw_act.msrb_statement_ind,
       vw_act.pep,
       vw_act.first_name_pep,
       vw_act.last_name_pep,
       vw_act.suffix_pep,
       vw_act.political_office_held,
       vw_act.country_of_office,
       vw_act.foreign_bank_account_ind,
       vw_act.foreign_bank_cert_date,
       vw_act.foreign_bank_cert_exp_date,
       vw_act.central_bank_ind,
       vw_act.acct_foreign_financial_inst,
       vw_act.foreign_bank_acct_oper_1,
       vw_act.foreign_bank_acct_oper_2,
       vw_act.foreign_bank_acct_oper_3,
       vw_act.number_people_own,
       vw_act.proprietary_acct_owned,
       vw_act.tel_1_transaction_code,
       vw_act.tel_1_us_ind,
       vw_act.tel_1_type_id,
       vw_act.tel_1_number,
       vw_act.tel_1_extension,
       vw_act.tel_2_transaction_code,
       vw_act.tel_2_us_ind,
       vw_act.tel_2_type_id,
       vw_act.tel_2_number,
       vw_act.tel_2_extension,
       vw_act.tel_3_transaction_code,
       vw_act.tel_3_us_ind,
       vw_act.tel_3_type_id,
       vw_act.tel_3_number,
       vw_act.tel_3_extension,
       vw_act.tel_4_transaction_code,
       vw_act.tel_4_us_ind,
       vw_act.tel_4_type_id,
       vw_act.tel_4_number,
       vw_act.tel_4_extension,
       vw_act.tel_5_transaction_code,
       vw_act.tel_5_us_ind,
       vw_act.tel_5_type_id,
       vw_act.tel_5_number,
       vw_act.tel_5_extension,
       vw_act.tel_6_transaction_code,
       vw_act.tel_6_us_ind,
       vw_act.tel_6_type_id,
       vw_act.tel_6_number,
       vw_act.tel_6_extension,
       vw_act.tel_7_transaction_code,
       vw_act.tel_7_us_ind,
       vw_act.tel_7_type_id,
       vw_act.tel_7_number,
       vw_act.tel_7_extension,
       vw_act.tel_8_transaction_code,
       vw_act.tel_8_us_ind,
       vw_act.tel_8_type_id,
       vw_act.tel_8_number,
       vw_act.tel_8_extension,
       vw_act.email_address,
       vw_act.external_position_ind,
       vw_act.purge_eligible_ind,
       vw_act.advisory_acct_ind,
       vw_act.product_profile_code,
       vw_act.cents_per_share_discount,
       vw_act.option_disclosure_date,
       vw_act.country_acct_level_tax_residency
FROM pershing.vw_maestro_acct vw_act
         LEFT JOIN pershing.par_country_code par_cc_res ON vw_act.country_of_residence::text = par_cc_res.iso_code::text
         LEFT JOIN pershing.par_country_code par_cc_cit
                   ON vw_act.primary_country_of_citizenship::text = par_cc_cit.iso_code::text
         LEFT JOIN pershing.par_registration_type par_reg_type
                   ON vw_act.registration_type::text = par_reg_type.id::text;

alter table pershing.vw_maestro_cuenta
    owner to postgres;

