create table clientes.comision_cuenta
(
    id                    bigint generated by default as identity,
    id_cuenta             integer                              not null,
    comision_diaria_saldo numeric(45, 20) default NULL::numeric,
    fecha_inicio_vigencia date            default CURRENT_DATE not null,
    log_fecha_creacion    timestamp       default now()        not null,
    log_usuario_creacion  varchar(100)                         not null,
    constraint comision_cuenta_pk
        primary key (id),
    constraint comision_cuenta_cuenta_fk
        foreign key (id_cuenta) references clientes.cuenta
);

alter table clientes.comision_cuenta
    owner to postgres;

