create table pershing.sfl_gact
(
    id                                       bigint generated always as identity,
    id_proceso                               bigint       not null,
    process_date                             varchar(100) not null,
    record_id_sequence_number                integer,
    account_number                           varchar(100),
    cusip_number                             varchar(100),
    underlying_cusip                         varchar(100),
    security_symbol                          varchar(100),
    investment_professional_of_record        varchar(100),
    executing_investment_professional        varchar(100),
    transaction_type                         varchar(100),
    buy_sell_code                            varchar(100),
    open_close_indicator                     varchar(100),
    par_key_code                             varchar(100),
    source_code                              varchar(100),
    maxx_key_code                            integer,
    process_date_sfl                         date,
    trade_date                               date,
    settlement_entry_date                    date,
    source_of_input                          varchar(100),
    reference_number                         varchar(100),
    batch_code                               varchar(100),
    same_day_settlement                      varchar(100),
    contra_account                           varchar(100),
    market_code                              varchar(100),
    blotter_code                             varchar(100),
    cancel_code                              varchar(100),
    correction_code                          varchar(100),
    merket_limit_indicator                   varchar(100),
    legend_code_1                            varchar(100),
    legend_code_2                            varchar(100),
    quantity                                 numeric(45, 20),
    price_in_trade_currency                  numeric(45, 20),
    currency_indicator_for_price             varchar(100),
    net_amount_in_usd                        numeric(45, 20),
    principal_in_usd                         numeric(45, 20),
    interest_in_usd                          numeric(45, 20),
    commision_in_usd                         numeric(45, 20),
    tax_in_usd                               numeric(45, 20),
    transaction_fee_in_usd                   numeric(45, 20),
    misc_fee_in_usd                          numeric(45, 20),
    other_fee_in_usd                         numeric(45, 20),
    tefra_wh_amount_in_usd                   numeric(45, 20),
    pershing_charge_in_usd                   numeric(45, 20),
    brokerage_charge_in_usd                  numeric(45, 20),
    sales_credit_in_usd                      numeric(45, 20),
    settlement_fee_in_usd                    numeric(45, 20),
    service_charge_in_usd                    numeric(45, 20),
    markup_markdown_amount_in_usd            numeric(45, 20),
    dividend_payable_date                    date,
    dividend_record_date                     date,
    dividend_type                            integer,
    shares_of_record_quantity_for_dividends  numeric(45, 20),
    order_size_quantity                      numeric(45, 20),
    pool_factor                              numeric(45, 20),
    parsed_customer_account_number           varchar(100),
    ibd_number                               varchar(100),
    security_type_code                       varchar(100),
    security_modifier_code                   varchar(100),
    security_calculation_code                varchar(100),
    minor_product_code                       varchar(100),
    foreign_product_indicator                varchar(100),
    with_due_bill_indicator                  varchar(100),
    taxable_municipal_bond_indicator         varchar(100),
    omnibus_indicator                        varchar(100),
    external_order_id                        varchar(100),
    market_value_of_transaction              numeric(45, 20),
    ip_number_parsed                         varchar(100),
    reported_price                           numeric(45, 20),
    previous_day_market_value_of_transaction numeric(45, 20),
    price_in_usd                             numeric(45, 20),
    option_root_id                           varchar(100),
    expiration_date                          date,
    put_call_code                            varchar(100),
    strike_price                             numeric(45, 20),
    repo_identifier                          varchar(100),
    taxable                                  varchar(100),
    qualified                                varchar(100),
    expanded_ip_number                       varchar(100),
    expanded_exec_ip_number                  varchar(100),
    expanded_legacy_ip_number                varchar(100),
    security_currency_of_issuance            varchar(100),
    trade_currency_code                      varchar(100),
    settlement_currency_code                 varchar(100),
    settlement_usd_currency_fx_rate          numeric(45, 20),
    settlement_usd_multiply_divide_code      varchar(100),
    cross_currency_fx_rate                   numeric(45, 20),
    currency_multiply_divide_code            varchar(100),
    accrued_interest_in_settlement_currency  numeric(45, 20),
    internal_reference_for_gloss             varchar(100),
    ibd_version                              varchar(100),
    net_amount_in_settlement_currency        numeric(45, 20),
    principal_amount_in_settlement_currency  numeric(45, 20),
    interest_in_settlement_currency          numeric(45, 20),
    commission_in_settlement_currency        numeric(45, 20),
    tax_in_settlement_currency               numeric(45, 20),
    transaction_fee_in_settlement_currency   numeric(45, 20),
    miscellaneous_fee_in_settlement_currency numeric(45, 20),
    other_fee_in_settlement_currency         numeric(45, 20),
    sales_credit_in_settlement_currency      numeric(45, 20),
    settlement_fee_in_settlement_currency    numeric(45, 20),
    service_charge_in_settlement_currency    numeric(45, 20),
    markup_markdown_in_settlement_currency   numeric(45, 20),
    global_exchange                          varchar(100),
    number_of_description_lines              integer,
    last_description_line                    integer,
    description_line_1                       varchar(100),
    description_line_2                       varchar(100),
    description_line_3                       varchar(100),
    description_line_4                       varchar(100),
    description_line_5                       varchar(100),
    description_line_6                       varchar(100),
    description_line_7                       varchar(100),
    description_line_8                       varchar(100),
    description_line_9                       varchar(100),
    description_line_10                      varchar(100),
    description_line_11                      varchar(100),
    description_line_12                      varchar(100),
    security_currency_indicator              varchar(100),
    market_mnemonic_code                     varchar(100),
    ccy_of_issuance_usd_ccy_fx_rate          numeric(45, 20),
    ccy_of_issuance_usd_multiply_divide_code varchar(100),
    alternate_security_id_type               varchar(100),
    alternate_security_id                    varchar(100),
    alternate_security_id_type_2             varchar(100),
    alternate_security_id_2                  varchar(100),
    international_non_dollar_symbol          varchar(100),
    confirmation_code_1                      varchar(100),
    confirmation_code_2                      varchar(100),
    confirmation_code_3                      varchar(100),
    confirmation_code_4                      varchar(100),
    pmp                                      numeric(45, 20),
    total_amount_mark_up_down                numeric(45, 20),
    pmp_percent                              numeric(45, 20),
    constraint sfl_gact_pk
        primary key (id)
);

alter table pershing.sfl_gact
    owner to postgres;

