create table pershing.sfl_isca_historica
(
    id                                              bigint generated always as identity,
    id_proceso                                      bigint       not null,
    process_date                                    varchar(100) not null,
    cusip_number                                    varchar(100),
    security_type                                   varchar(100),
    security_modifier                               varchar(100),
    security_calculation_code                       varchar(100),
    primary_exchange                                varchar(100),
    coupon_rate_fis_or_indicated_dividend_eq        numeric(45, 20),
    maturity_option_expire_date                     date,
    underlying_security_cusip                       varchar(100),
    first_call_price_fix_inc_or_strike_price_option numeric(45, 20),
    first_par_call_price_fix_inc_or_units_option    numeric(45, 20),
    primary_symbol                                  varchar(100),
    interest_frequency                              varchar(100),
    bond_class                                      varchar(100),
    first_coupon_day                                varchar(100),
    call_indicator                                  varchar(100),
    put_indicator                                   varchar(100),
    next_par_call_date                              date,
    prerefunded_date                                date,
    next_premium_call_date                          date,
    dated_date_for_fix_inc_or_ex_dividend_date_eq   date,
    first_coupon_fix_inc_or_payable_date_eq         date,
    federal_marginable_ind                          varchar(100),
    cns_eligible_code                               varchar(100),
    dtcc_eligible_code                              varchar(100),
    nscc_eligible_code                              varchar(100),
    foreign_security                                varchar(100),
    second_coupon_day                               varchar(100),
    dividend_interest_payment_method                varchar(100),
    minor_product_code                              varchar(100),
    etf_indicator                                   varchar(100),
    bid_price                                       numeric(45, 20),
    ask_price                                       numeric(45, 20),
    previous_day_price                              numeric(45, 20),
    latest_price                                    numeric(45, 20),
    end_of_month_price                              numeric(45, 20),
    round_lot_quantity                              integer,
    dividend_reinvestment_eligibility_indicator     varchar(100),
    previous_price_date                             date,
    latest_price_date                               date,
    end_of_month_price_date                         date,
    record_date                                     date,
    fundvest_ind                                    varchar(100),
    country_code                                    varchar(100),
    standard_poor_rating                            varchar(100),
    moodys_rating                                   varchar(100),
    bond_sub_class                                  varchar(100),
    restriction_indicator                           varchar(100),
    trace_indicator                                 varchar(100),
    new_interest_calculation_code                   varchar(100),
    sic_code                                        varchar(100),
    state_tax_ind                                   varchar(100),
    fts_ind                                         varchar(100),
    amt_ind                                         varchar(100),
    ric_indicator                                   varchar(100),
    number_of_description_lines                     varchar(100),
    secutiry_description_line_1                     varchar(100),
    secutiry_description_line_2                     varchar(100),
    secutiry_description_line_3                     varchar(100),
    secutiry_description_line_4                     varchar(100),
    secutiry_description_line_5                     varchar(100),
    user_cusip_identifier                           varchar(100),
    price_purge_date                                date,
    taxable_indicator                               varchar(100),
    secutiry_description_line_6                     varchar(100),
    put_price                                       numeric(45, 20),
    put_date                                        date,
    second_premium_call_price                       numeric(45, 20),
    second_premium_call_date                        date,
    called_date                                     date,
    pool_number                                     varchar(100),
    factor                                          numeric(45, 20),
    factor_date                                     date,
    previous_factor                                 varchar(100),
    previous_factor_date                            date,
    variable_rate_indicator                         varchar(100),
    next_last_coupon_date                           date,
    structured_product_ind                          varchar(100),
    perpetual_bond_indicator                        varchar(100),
    exp_first_call_price                            numeric(45, 20),
    exp_first_par_call_price                        numeric(45, 20),
    exp_put_price                                   numeric(45, 20),
    exp_second_premium_call_price                   numeric(45, 20),
    name_issuer_security                            varchar(100),
    issuing_currency                                varchar(100),
    globally_locked_sec_ind                         varchar(100),
    globally_locked_reason_code                     varchar(100),
    spac_ind                                        varchar(100),
    eor                                             varchar(100),
    expanded_bid_price                              numeric(45, 20),
    expanded_ask_price                              numeric(45, 20),
    expanded_previous_day_price                     numeric(45, 20),
    expanded_latest_price                           numeric(45, 20),
    expanded_end_of_month_price                     numeric(45, 20),
    contract_share_quantity                         numeric(45, 20),
    year_covered_under_cost_basis_rules             integer,
    delta                                           numeric(45, 20),
    delta_value_presence_ind                        varchar(100),
    isin_code                                       varchar(100),
    issuer_identifier                               varchar(100),
    symbol_of_the_underlying_security               varchar(100),
    asset_type                                      varchar(100),
    asset_subtype                                   varchar(100),
    asset_subsubtype                                varchar(100),
    payment_day_delays                              integer,
    exchange_rate_denom_currency_usd                numeric(45, 20),
    underlying_cusip_1                              varchar(100),
    deliverable_unit_quantity_1                     integer,
    underlying_cusip_2                              varchar(100),
    deliverable_unit_quantity_2                     integer,
    underlying_cusip_3                              varchar(100),
    deliverable_unit_quantity_3                     integer,
    underlying_cusip_4                              varchar(100),
    deliverable_unit_quantity_4                     integer,
    annual_dividend_currency_code                   varchar(100),
    outstanding_shares                              numeric(45, 20),
    option_root_id                                  varchar(100),
    expiration_date                                 date,
    call_put_indicator                              varchar(100),
    strike_price                                    numeric(45, 20),
    fund_type                                       varchar(100),
    broad_narrow_indicator                          varchar(100),
    leverage_factor                                 numeric(45, 20),
    outstanding_shares_update_date                  date,
    expanded_symbol                                 varchar(100),
    state_of_issuance                               varchar(100),
    option_excercise_pricing_model_code             varchar(100),
    first_accrual_date                              date,
    tranche_code                                    varchar(100),
    worthless_security_indicator                    varchar(100),
    uit_termination_code                            integer,
    fdic_certification_number                       varchar(100),
    revenue_stream                                  varchar(100),
    restricted_marijuana_ind                        varchar(100),
    factored_market_value_multiplier                numeric(45, 20),
    current_yield                                   numeric(45, 20),
    yield                                           numeric(45, 20),
    price_source                                    varchar(100),
    country_of_origin                               varchar(100),
    retricted_security_code                         varchar(100),
    international_non_dollar_symbol                 varchar(100),
    international_exchange                          varchar(100),
    variable_rate_category_code                     varchar(100),
    interest_rate_completion_ind                    varchar(100),
    exchange_code_sedol_1                           varchar(100),
    sedol_1                                         varchar(100),
    exchange_code_sedol_2                           varchar(100),
    sedol_2                                         varchar(100),
    exchange_code_sedol_3                           varchar(100),
    sedol_3                                         varchar(100),
    exchange_code_sedol_4                           varchar(100),
    sedol_4                                         varchar(100),
    exchange_code_sedol_5                           varchar(100),
    sedol_5                                         varchar(100),
    exchange_code_sedol_6                           varchar(100),
    sedol_6                                         varchar(100),
    exchange_code_sedol_7                           varchar(100),
    sedol_7                                         varchar(100),
    exchange_code_sedol_8                           varchar(100),
    sedol_8                                         varchar(100),
    exchange_code_sedol_9                           varchar(100),
    sedol_9                                         varchar(100),
    exchange_code_sedol_10                          varchar(100),
    sedol_10                                        varchar(100),
    exchange_code_sedol_11                          varchar(100),
    sedol_11                                        varchar(100),
    primary_idc_mkt_exch                            varchar(100),
    primary_mkt_exch_trading_status                 varchar(100),
    primary_mkt_symbol                              varchar(100),
    primary_mkt_exch_effective_date                 date,
    primary_mkt_status_code                         varchar(100),
    secondary_idc_mkt_exch                          varchar(100),
    secondary_mkt_exch_trading_status               varchar(100),
    secondary_mkt_symbol                            varchar(100),
    secondary_mkt_exch_effective_date               date,
    secondary_mkt_status_code                       varchar(100),
    tick_size_pilot_group                           varchar(100),
    tick_size_effective_date                        date,
    tick_size_change_date                           date,
    update_date                                     date,
    oas_libor_rate                                  numeric(45, 20),
    first_call_date                                 date,
    first_call_price                                numeric(45, 20),
    second_call_date                                date,
    second_call_price                               numeric(45, 20),
    third_call_date                                 date,
    third_call_price                                numeric(45, 20),
    fourth_call_date                                date,
    fourth_call_price                               numeric(45, 20),
    effective_date_rate_1                           date,
    coupon_interest_rate_1                          numeric(45, 20),
    effective_date_rate_2                           date,
    coupon_interest_rate_2                          numeric(45, 20),
    effective_date_rate_3                           date,
    coupon_interest_rate_3                          numeric(45, 20),
    effective_date_rate_4                           date,
    coupon_interest_rate_4                          numeric(45, 20),
    oas_treasury_rate                               numeric(45, 20),
    oas_treasury_effective_date                     date,
    minimum_piece                                   numeric(45, 20),
    minimum_increment                               numeric(45, 20),
    issue_date_security                             date,
    constraint sfl_isca_historica_pk
        primary key (id)
);

alter table pershing.sfl_isca_historica
    owner to postgres;

