create or replace function stage_pershing.fn_extrae_acct_reg_a(_id_proceso bigint)
    returns TABLE(id bigint, id_proceso bigint, process_date character varying, transaction_code character varying, record_indicator_value character varying, record_id_sequence_number character varying, account_number character varying, ibd_number character varying, campo_6 character varying, ip_number character varying, account_short_name character varying, campo_9 character varying, transaction_type character varying, autotitled_usertitled_account character varying, account_type_code character varying, registration_type character varying, campo_14 character varying, number_of_account_title_lines character varying, account_registration_line_1 character varying, account_registration_line_2 character varying, account_registration_line_3 character varying, account_registration_line_4 character varying, account_registration_line_5 character varying, account_registration_line_6 character varying, registration_type_detail character varying, date_account_opened character varying, date_account_information_updated character varying, account_status_indicator character varying, pending_closed_date character varying, date_account_closed character varying, closing_notice_date character varying, account_reactivated_date character varying, date_account_reopened character varying, proceeds character varying, transfer_instructions character varying, income_isntructions character varying, number_of_confirms_for_thi_account character varying, number_of_statements_for_this_account character varying, investment_objetive_trans_code character varying, comments_act character varying, employer_shotname character varying, employers_cusip character varying, employers_symbol character varying, margin_privileges_revoked character varying, statement_review_date character varying, margin_papers_on_file character varying, option_papers_on_file character varying, campo_45 character varying, good_faith_margin character varying, ip_discretion_granted character varying, invest_advisor_discretion_granted character varying, third_party_discretion_granted character varying, third_party_name character varying, risk_factor_code character varying, investment_objetive_code character varying, option_equities character varying, option_index character varying, option_debt character varying, option_currency character varying, option_level_1 character varying, option_level_2 character varying, option_level_3 character varying, option_level_4 character varying, option_call_limits character varying, option_put_limits character varying, option_total_limits_of_puts_and_calls character varying, non_us_dollar_trading character varying, campo_65 character varying, non_customer_indicator character varying, third_party_fee_indicator character varying, third_party_fee_approval_date character varying, intermediary_account_ind character varying, commission_schedule character varying, group_index character varying, money_manager_id character varying, money_manager_objective_id character varying, dtc_id_confirm_number character varying, caps_master_mnemonic character varying, employee_id character varying, prime_broker_free_fund_indicator character varying, fee_based_account_indicator character varying, campo_79 character varying, fee_based_termination_date character varying, campo_81 character varying, plan_name character varying, self_directed_401_k_account_type character varying, plan_type character varying, plan_number character varying, employee_or_employee_relative character varying, commission_percent_discount character varying, ind_12_b_1_fee_blocking character varying, name_of_ip_signed_new_account_form character varying, date_of_ip_signed_new_account_form character varying, name_of_principal_signed_new_account_form character varying, date_of_principal_signed_new_account_form character varying, politically_exposed_person character varying, private_banking_account character varying, foreign_bank_account character varying, initial_source_of_funds character varying, usa_patriot_act_exempt_reason character varying, primary_country_of_citizenship character varying, country_of_residence character varying, birth_date character varying, age_based_fund_roll_exempt character varying, money_fundreform_retail character varying, trusted_contact_status character varying, regulatory_account_type_category character varying, account_managed_by_trust_comp_id character varying, voting_auth character varying, campo_107 character varying, campo_108 character varying, campo_109 character varying, campo_110 character varying, customer_type character varying, campo_112 character varying, campo_113 character varying, campo_114 character varying, campo_115 character varying, campo_116 character varying, fulfillment_method character varying, credit_interest_indicator character varying, ama_indicator character varying, campo_120 character varying, eor character varying)
    language plpgsql
as
$$
    BEGIN

    RETURN QUERY
    SELECT sfl_file.id, sfl_file.id_proceso, sfl_file.process_date,
        substr(sfl_file.linea, 1, 2)::VARCHAR(100) as transaction_code,
        substr(sfl_file.linea, 3, 1)::VARCHAR(100) as record_indicator_value,
        substr(sfl_file.linea, 4, 8)::VARCHAR(100) as record_id_sequence_number,
        substr(sfl_file.linea, 12, 9)::VARCHAR(100) as account_number,
        substr(sfl_file.linea, 21, 3)::VARCHAR(100) as ibd_number,
        substr(sfl_file.linea, 24, 1)::VARCHAR(100) as campo_6,
        substr(sfl_file.linea, 25, 4)::VARCHAR(100) as ip_number,
        substr(sfl_file.linea, 29, 10)::VARCHAR(100) as account_short_name,
        substr(sfl_file.linea, 39, 2)::VARCHAR(100) as campo_9,
        substr(sfl_file.linea, 41, 1)::VARCHAR(100) as transaction_type,
        substr(sfl_file.linea, 42, 1)::VARCHAR(100) as autotitled_usertitled_account,
        substr(sfl_file.linea, 43, 1)::VARCHAR(100) as account_type_code,
        substr(sfl_file.linea, 44, 4)::VARCHAR(100) as registration_type,
        substr(sfl_file.linea, 48, 1)::VARCHAR(100) as campo_14,
        substr(sfl_file.linea, 49, 1)::VARCHAR(100) as number_of_account_title_lines,
        substr(sfl_file.linea, 50, 32)::VARCHAR(100) as account_registration_line_1,
        substr(sfl_file.linea, 82, 32)::VARCHAR(100) as account_registration_line_2,
        substr(sfl_file.linea, 114, 32)::VARCHAR(100) as account_registration_line_3,
        substr(sfl_file.linea, 146, 32)::VARCHAR(100) as account_registration_line_4,
        substr(sfl_file.linea, 178, 32)::VARCHAR(100) as account_registration_line_5,
        substr(sfl_file.linea, 210, 32)::VARCHAR(100) as account_registration_line_6,
        substr(sfl_file.linea, 242, 21)::VARCHAR(100) as registration_type_detail,
        substr(sfl_file.linea, 263, 8)::VARCHAR(100) as date_account_opened,
        substr(sfl_file.linea, 271, 8)::VARCHAR(100) as date_account_information_updated,
        substr(sfl_file.linea, 279, 1)::VARCHAR(100) as account_status_indicator,
        substr(sfl_file.linea, 280, 8)::VARCHAR(100) as pending_closed_date,
        substr(sfl_file.linea, 288, 8)::VARCHAR(100) as date_account_closed,
        substr(sfl_file.linea, 296, 8)::VARCHAR(100) as closing_notice_date,
        substr(sfl_file.linea, 304, 8)::VARCHAR(100) as account_reactivated_date,
        substr(sfl_file.linea, 312, 8)::VARCHAR(100) as date_account_reopened,
        substr(sfl_file.linea, 320, 1)::VARCHAR(100) as proceeds,
        substr(sfl_file.linea, 321, 1)::VARCHAR(100) as transfer_instructions,
        substr(sfl_file.linea, 322, 1)::VARCHAR(100) as income_isntructions,
        substr(sfl_file.linea, 323, 2)::VARCHAR(100) as number_of_confirms_for_thi_account,
        substr(sfl_file.linea, 325, 2)::VARCHAR(100) as number_of_statements_for_this_account,
        substr(sfl_file.linea, 327, 1)::VARCHAR(100) as investment_objetive_trans_code,
        substr(sfl_file.linea, 328, 26)::VARCHAR(100) as comments_act,
        substr(sfl_file.linea, 354, 15)::VARCHAR(100) as employer_shotname,
        substr(sfl_file.linea, 369, 9)::VARCHAR(100) as employers_cusip,
        substr(sfl_file.linea, 378, 9)::VARCHAR(100) as employers_symbol,
        substr(sfl_file.linea, 387, 1)::VARCHAR(100) as margin_privileges_revoked,
        substr(sfl_file.linea, 388, 8)::VARCHAR(100) as statement_review_date,
        substr(sfl_file.linea, 396, 1)::VARCHAR(100) as margin_papers_on_file,
        substr(sfl_file.linea, 397, 1)::VARCHAR(100) as option_papers_on_file,
        substr(sfl_file.linea, 398, 1)::VARCHAR(100) as campo_45,
        substr(sfl_file.linea, 399, 1)::VARCHAR(100) as good_faith_margin,
        substr(sfl_file.linea, 400, 1)::VARCHAR(100) as ip_discretion_granted,
        substr(sfl_file.linea, 401, 1)::VARCHAR(100) as invest_advisor_discretion_granted,
        substr(sfl_file.linea, 402, 1)::VARCHAR(100) as third_party_discretion_granted,
        substr(sfl_file.linea, 403, 15)::VARCHAR(100) as third_party_name,
        substr(sfl_file.linea, 418, 1)::VARCHAR(100) as risk_factor_code,
        substr(sfl_file.linea, 419, 4)::VARCHAR(100) as investment_objetive_code,
        substr(sfl_file.linea, 423, 1)::VARCHAR(100) as option_equities,
        substr(sfl_file.linea, 424, 1)::VARCHAR(100) as option_index,
        substr(sfl_file.linea, 425, 1)::VARCHAR(100) as option_debt,
        substr(sfl_file.linea, 426, 1)::VARCHAR(100) as option_currency,
        substr(sfl_file.linea, 427, 1)::VARCHAR(100) as option_level_1,
        substr(sfl_file.linea, 428, 1)::VARCHAR(100) as option_level_2,
        substr(sfl_file.linea, 429, 1)::VARCHAR(100) as option_level_3,
        substr(sfl_file.linea, 430, 1)::VARCHAR(100) as option_level_4,
        substr(sfl_file.linea, 431, 10)::VARCHAR(100) as option_call_limits,
        substr(sfl_file.linea, 441, 10)::VARCHAR(100) as option_put_limits,
        substr(sfl_file.linea, 451, 10)::VARCHAR(100) as option_total_limits_of_puts_and_calls,
        substr(sfl_file.linea, 461, 1)::VARCHAR(100) as non_us_dollar_trading,
        substr(sfl_file.linea, 462, 3)::VARCHAR(100) as campo_65,
        substr(sfl_file.linea, 465, 1)::VARCHAR(100) as non_customer_indicator,
        substr(sfl_file.linea, 466, 2)::VARCHAR(100) as third_party_fee_indicator,
        substr(sfl_file.linea, 468, 8)::VARCHAR(100) as third_party_fee_approval_date,
        substr(sfl_file.linea, 476, 1)::VARCHAR(100) as intermediary_account_ind,
        substr(sfl_file.linea, 477, 2)::VARCHAR(100) as commission_schedule,
        substr(sfl_file.linea, 479, 5)::VARCHAR(100) as group_index,
        substr(sfl_file.linea, 484, 3)::VARCHAR(100) as money_manager_id,
        substr(sfl_file.linea, 487, 3)::VARCHAR(100) as money_manager_objective_id,
        substr(sfl_file.linea, 490, 5)::VARCHAR(100) as dtc_id_confirm_number,
        substr(sfl_file.linea, 495, 9)::VARCHAR(100) as caps_master_mnemonic,
        substr(sfl_file.linea, 504, 8)::VARCHAR(100) as employee_id,
        substr(sfl_file.linea, 512, 1)::VARCHAR(100) as prime_broker_free_fund_indicator,
        substr(sfl_file.linea, 513, 1)::VARCHAR(100) as fee_based_account_indicator,
        substr(sfl_file.linea, 514, 3)::VARCHAR(100) as campo_79,
        substr(sfl_file.linea, 517, 8)::VARCHAR(100) as fee_based_termination_date,
        substr(sfl_file.linea, 525, 1)::VARCHAR(100) as campo_81,
        substr(sfl_file.linea, 526, 32)::VARCHAR(100) as plan_name,
        substr(sfl_file.linea, 558, 32)::VARCHAR(100) as self_directed_401_k_account_type,
        substr(sfl_file.linea, 590, 2)::VARCHAR(100) as plan_type,
        substr(sfl_file.linea, 592, 10)::VARCHAR(100) as plan_number,
        substr(sfl_file.linea, 602, 4)::VARCHAR(100) as employee_or_employee_relative,
        substr(sfl_file.linea, 606, 18)::VARCHAR(100) as commission_percent_discount,
        substr(sfl_file.linea, 624, 1)::VARCHAR(100) as ind_12_b_1_fee_blocking,
        substr(sfl_file.linea, 625, 15)::VARCHAR(100) as name_of_ip_signed_new_account_form,
        substr(sfl_file.linea, 640, 8)::VARCHAR(100) as date_of_ip_signed_new_account_form,
        substr(sfl_file.linea, 648, 15)::VARCHAR(100) as name_of_principal_signed_new_account_form,
        substr(sfl_file.linea, 663, 8)::VARCHAR(100) as date_of_principal_signed_new_account_form,
        substr(sfl_file.linea, 671, 1)::VARCHAR(100) as politically_exposed_person,
        substr(sfl_file.linea, 672, 1)::VARCHAR(100) as private_banking_account,
        substr(sfl_file.linea, 673, 1)::VARCHAR(100) as foreign_bank_account,
        substr(sfl_file.linea, 674, 4)::VARCHAR(100) as initial_source_of_funds,
        substr(sfl_file.linea, 678, 4)::VARCHAR(100) as usa_patriot_act_exempt_reason,
        substr(sfl_file.linea, 682, 2)::VARCHAR(100) as primary_country_of_citizenship,
        substr(sfl_file.linea, 684, 2)::VARCHAR(100) as country_of_residence,
        substr(sfl_file.linea, 686, 8)::VARCHAR(100) as birth_date,
        substr(sfl_file.linea, 694, 1)::VARCHAR(100) as age_based_fund_roll_exempt,
        substr(sfl_file.linea, 695, 1)::VARCHAR(100) as money_fundreform_retail,
        substr(sfl_file.linea, 696, 1)::VARCHAR(100) as trusted_contact_status,
        substr(sfl_file.linea, 697, 4)::VARCHAR(100) as regulatory_account_type_category,
        substr(sfl_file.linea, 701, 1)::VARCHAR(100) as account_managed_by_trust_comp_id,
        substr(sfl_file.linea, 702, 2)::VARCHAR(100) as voting_auth,
        substr(sfl_file.linea, 704, 6)::VARCHAR(100) as campo_107,
        substr(sfl_file.linea, 710, 2)::VARCHAR(100) as campo_108,
        substr(sfl_file.linea, 712, 3)::VARCHAR(100) as campo_109,
        substr(sfl_file.linea, 715, 4)::VARCHAR(100) as campo_110,
        substr(sfl_file.linea, 719, 4)::VARCHAR(100) as customer_type,
        substr(sfl_file.linea, 723, 4)::VARCHAR(100) as campo_112,
        substr(sfl_file.linea, 727, 4)::VARCHAR(100) as campo_113,
        substr(sfl_file.linea, 731, 4)::VARCHAR(100) as campo_114,
        substr(sfl_file.linea, 735, 4)::VARCHAR(100) as campo_115,
        substr(sfl_file.linea, 739, 4)::VARCHAR(100) as campo_116,
        substr(sfl_file.linea, 743, 4)::VARCHAR(100) as fulfillment_method,
        substr(sfl_file.linea, 747, 1)::VARCHAR(100) as credit_interest_indicator,
        substr(sfl_file.linea, 748, 1)::VARCHAR(100) as ama_indicator,
        substr(sfl_file.linea, 749, 1)::VARCHAR(100) as campo_120,
        substr(sfl_file.linea, 750, 1)::VARCHAR(100) as eor

    FROM stage_pershing.stage_acct_file sfl_file WHERE sfl_file.id_proceso = COALESCE(_id_proceso, sfl_file.id_proceso)
    --AND SUBSTRING(sfl_file.linea, 1, 18)		= 'BOF      PERSHING '
    --AND SUBSTRING(sfl_file.linea, 1, 18)		= 'EOF      PERSHING '
    AND SUBSTRING(sfl_file.linea, 1, 3)		= 'CIA'
    ORDER BY sfl_file.id;

    RETURN;
    END;
$$;

alter function stage_pershing.fn_extrae_acct_reg_a(bigint) owner to postgres;

