create or replace function stage_pershing.fn_parse_acct_reg_b(_id_proceso bigint) returns SETOF stage_pershing.stage_acct_reg_b
    language plpgsql
as
$$
    BEGIN

    RETURN QUERY
    SELECT
        fn_reg.id::BIGINT, fn_reg.id_proceso::BIGINT, fn_reg.process_date::VARCHAR(100),
        fn_reg.transaction_code::VARCHAR(100),
        fn_reg.record_indicator_value::VARCHAR(100),
        fn_reg.record_id_sequence_number::int as record_id_sequence_number,
        fn_reg.account_number::VARCHAR(100),
        fn_reg.ibd_number::VARCHAR(100),
        fn_reg.campo_6::VARCHAR(100),
        fn_reg.ip_number::VARCHAR(100),
        fn_reg.account_short_name::VARCHAR(100),
        fn_reg.campo_9::VARCHAR(100),
        fn_reg.tax_id_type::VARCHAR(100),
        fn_reg.tax_id_number::VARCHAR(100),
        public.fn_fecha_string_to_date(fn_reg.date_tax_id_applied_for, 'CCYYMMDD')::DATE as date_tax_id_applied_for,
        fn_reg.w_8_w_9_indicator::VARCHAR(100),
        public.fn_fecha_string_to_date(fn_reg.w_8_w_9_date_signed, 'CCYYMMDD')::DATE as w_8_w_9_date_signed,
        public.fn_fecha_string_to_date(fn_reg.w_8_w_9_effective_date, 'CCYYMMDD')::DATE as w_8_w_9_effective_date,
        fn_reg.w_8_w_9_document_type::VARCHAR(100),
        fn_reg.tax_status::VARCHAR(100),
        fn_reg.b_notice_reason_code::VARCHAR(100),
        fn_reg.first_b_notice_status::VARCHAR(100),
        public.fn_fecha_string_to_date(fn_reg.date_first_b_notice_status_issued_enforced, 'CCYYMMDD')::DATE as date_first_b_notice_status_issued_enforced,
        fn_reg.campo_21::VARCHAR(100),
        public.fn_fecha_string_to_date(fn_reg.date_first_notice_status_satisfied, 'CCYYMMDD')::DATE as date_first_notice_status_satisfied,
        fn_reg.second_b_notice_status::VARCHAR(100),
        public.fn_fecha_string_to_date(fn_reg.date_second_b_notice_status_issued_enforced, 'CCYYMMDD')::DATE as date_second_b_notice_status_issued_enforced,
        fn_reg.campo_25::VARCHAR(100),
        public.fn_fecha_string_to_date(fn_reg.date_second_b_notice_status_satisfied, 'CCYYMMDD')::DATE as date_second_b_notice_status_satisfied,
        fn_reg.c_notice_status::VARCHAR(100),
        public.fn_fecha_string_to_date(fn_reg.date_c_notice_status_issued_enforced, 'CCYYMMDD')::DATE as date_c_notice_status_issued_enforced,
        public.fn_fecha_string_to_date(fn_reg.date_c_notice_status_satisfied, 'CCYYMMDD')::DATE as date_c_notice_status_satisfied,
        fn_reg.old_account_number::VARCHAR(100),
        public.fn_fecha_string_to_date(fn_reg.original_account_open_date, 'CCYYMMDD')::DATE as original_account_open_date,
        fn_reg.unidentified_large_trader_id::VARCHAR(100),
        fn_reg.campo_33::VARCHAR(100),
        fn_reg.large_trader_type_code::VARCHAR(100),
        public.fn_fecha_string_to_date(fn_reg.large_trader_type_last_change_date, 'CCYYMMDD')::DATE as large_trader_type_last_change_date,
        fn_reg.campo_36::VARCHAR(100),
        fn_reg.campo_37::VARCHAR(100),
        fn_reg.initial_source_of_funds_other::VARCHAR(100),
        fn_reg.finance_away::VARCHAR(100),
        public.fn_fecha_string_to_date(fn_reg.account_funding_date, 'CCYYMMDD')::DATE as account_funding_date,
        fn_reg.campo_41::VARCHAR(100),
        fn_reg.statement_currency_code::VARCHAR(100),
        fn_reg.future_statement_currency_code::VARCHAR(100),
        public.fn_fecha_string_to_date(fn_reg.future_statement_currency_code_effective_date, 'CCYYMMDD')::DATE as future_statement_currency_code_effective_date,
        fn_reg.account_level_routing_code_1::VARCHAR(100),
        fn_reg.account_level_routing_code_2::VARCHAR(100),
        fn_reg.account_level_routing_code_3::VARCHAR(100),
        fn_reg.account_level_routing_code_4::VARCHAR(100),
        fn_reg.campo_49::VARCHAR(100),
        fn_reg.self_directed_ind::VARCHAR(100),
        fn_reg.digital_advice_ind::VARCHAR(100),
        fn_reg.pte_account_ind::VARCHAR(100),
        fn_reg.campo_53::VARCHAR(100),
        fn_reg.first_ip::VARCHAR(100),
        fn_reg.second_ip::VARCHAR(100),
        fn_reg.third_ip::VARCHAR(100),
        fn_reg.fourth_ip::VARCHAR(100),
        fn_reg.fifth_ip::VARCHAR(100),
        fn_reg.sixth_ip::VARCHAR(100),
        fn_reg.seventh_ip::VARCHAR(100),
        fn_reg.eighth_ip::VARCHAR(100),
        fn_reg.ninth_ip::VARCHAR(100),
        fn_reg.tenth_ip::VARCHAR(100),
        fn_reg.alert_im_acornym::VARCHAR(100),
        fn_reg.alert_im_access_code::VARCHAR(100),
        fn_reg.broker_acronym::VARCHAR(100),
        fn_reg.cross_reference_indicator::VARCHAR(100),
        fn_reg.bny_trust_indicator::VARCHAR(100),
        fn_reg.source_of_asset_at_acct_opening::VARCHAR(100),
        fn_reg.commission_doscount_code::VARCHAR(100),
        fn_reg.external_account_number::VARCHAR(100),
        fn_reg.confirmation_suppression_indicator::VARCHAR(100),
        public.fn_fecha_string_to_date(fn_reg.date_last_mail_sent, 'CCYYMM')::DATE as date_last_mail_sent,
        public.fn_fecha_string_to_date(fn_reg.date_last_mail_sent_outside, 'CCYYMM')::DATE as date_last_mail_sent_outside,
        fn_reg.campo_75::VARCHAR(100),
        fn_reg.fully_paid_lending_agreement_indicator::VARCHAR(100),
        public.fn_fecha_string_to_date(fn_reg.fully_paid_lending_agreement_date, 'CCYYMMDD')::DATE as fully_paid_lending_agreement_date,
        fn_reg.custodian_account_type::VARCHAR(100),
        fn_reg.mifid_customer_categorization::VARCHAR(100),
        fn_reg.cash_management_tran_code::VARCHAR(100),
        fn_reg.sweep_status_indicator::VARCHAR(100),
        public.fn_fecha_string_to_date(fn_reg.date_sweep_activated, 'CCYYMMDD')::DATE as date_sweep_activated,
        public.fn_fecha_string_to_date(fn_reg.date_sweep_details_changed, 'CCYYMMDD')::DATE as date_sweep_details_changed,
        fn_reg.cober_margin_debit_indicator::VARCHAR(100),
        fn_reg.campo_85::VARCHAR(100),
        fn_reg.first_fund_sweep_account_id::VARCHAR(100),
        public.fn_convierte_texto_numerico_cobol(fn_reg.firstfund_sweep_account_percent, 9)::NUMERIC(45,20) as firstfund_sweep_account_percent,
        fn_reg.first_fundsweep_account_redemption_priority::VARCHAR(100),
        fn_reg.second_fund_sweep_account_id::VARCHAR(100),
        public.fn_convierte_texto_numerico_cobol(fn_reg.second_fund_sweep_account_percent, 9)::NUMERIC(45,20) as second_fund_sweep_account_percent,
        fn_reg.second_fundsweep_account_redemption_priority::VARCHAR(100),
        fn_reg.type_of_bank_account::VARCHAR(100),
        fn_reg.banklink_aba_number::VARCHAR(100),
        fn_reg.banklink_dda_number::VARCHAR(100),
        fn_reg.campo_95::VARCHAR(100),
        fn_reg.fund_bank_indicator::VARCHAR(100),
        fn_reg.campo_97::VARCHAR(100),
        fn_reg.w_9_corp_tax_classification_code::VARCHAR(100),
        fn_reg.campo_99::VARCHAR(100),
        fn_reg.combined_margin_acct_indicator::VARCHAR(100),
        fn_reg.pledge_collateral_account_indicator::VARCHAR(100),
        fn_reg.finra_institutional_account_code::VARCHAR(100),
        fn_reg.proposed_account_reference_id::VARCHAR(100),
        fn_reg.advisor_model_id::VARCHAR(100),
        fn_reg.firm_model_style_id::VARCHAR(100),
        fn_reg.campo_106::VARCHAR(100),
        fn_reg.campo_107::VARCHAR(100),
        fn_reg.campo_108::VARCHAR(100),
        fn_reg.dvp_restriction_code::VARCHAR(100),
        public.fn_fecha_string_to_date(fn_reg.dvp_restriction_exp_date, 'CCYYMMDD')::DATE as dvp_restriction_exp_date,
        fn_reg.escheatment_withholding_ind::VARCHAR(100),
        fn_reg.campo_112::VARCHAR(100),
        fn_reg.source_of_origination::VARCHAR(100),
        fn_reg.source_of_persona::VARCHAR(100),
        fn_reg.client_onboarding_method::VARCHAR(100),
        fn_reg.tax_filing_code::VARCHAR(100),
        fn_reg.campo_117::VARCHAR(100),
        fn_reg.campo_118::VARCHAR(100),
        fn_reg.nor_purpose_collateral_acct_ind::VARCHAR(100),
        fn_reg.eor::VARCHAR(100)

    FROM stage_pershing.fn_extrae_acct_reg_b(_id_proceso) fn_reg
    ORDER BY fn_reg.id;

    RETURN;
    END;
$$;

alter function stage_pershing.fn_parse_acct_reg_b(bigint) owner to postgres;

