create or replace procedure stage_pershing.pa_parse_gact(IN _id_proceso bigint)
    language plpgsql
as
$$
DECLARE _cursor_reg_modif refcursor;
DECLARE _reg_modif record;
DECLARE _process_date VARCHAR(100);
begin

    DELETE FROM stage_pershing.stage_gact_reg_header reg_del WHERE reg_del.id_proceso=_id_proceso;
    DELETE FROM stage_pershing.stage_gact_reg_a reg_del WHERE reg_del.id_proceso=_id_proceso;
    DELETE FROM stage_pershing.stage_gact_reg_b reg_del WHERE reg_del.id_proceso=_id_proceso;
    DELETE FROM stage_pershing.stage_gact_reg_trailer reg_del WHERE reg_del.id_proceso=_id_proceso;

    INSERT INTO stage_pershing.stage_gact_reg_header (id_proceso, process_date, bof, campo_2, campo_3, date_of_data, campo_5, remote_id, campo_7, run_date, campo_9, run_time, campo_11, eor)
    SELECT id_proceso, process_date, bof, campo_2, campo_3, date_of_data, campo_5, remote_id, campo_7, run_date, campo_9, run_time, campo_11, eor
    FROM stage_pershing.fn_parse_gact_reg_header(_id_proceso);

    INSERT INTO stage_pershing.stage_gact_reg_a (id_proceso, process_date, transaction_code, record_indicator_value, record_id_sequence_number, account_number, cusip_number, campo_6, underlying_cusip, campo_8, security_symbol, investment_professional_of_record, executing_investment_professional, transaction_type, buy_sell_code, open_close_indicator, par_key_code, source_code, maxx_key_code, process_date_sfl, trade_date, settlement_entry_date, campo_21, source_of_input, reference_number, batch_code, same_day_settlement, contra_account, market_code, blotter_code, cancel_code, correction_code, merket_limit_indicator, legend_code_1, legend_code_2, campo_34, quantity, quantity_sign, price_in_trade_currency, campo_38, price_in_trade_currency_sign, currency_indicator_for_price, net_amount_in_usd, net_amount_in_usd_sign, principal_in_usd, principal_in_usd_sign, interest_in_usd, interest_in_usd_sign, commision_in_usd, commision_in_usd_sign, tax_in_usd, tax_in_usd_sign, transaction_fee_in_usd, transaction_fee_in_usd_sign, misc_fee_in_usd, misc_fee_in_usd_sign, other_fee_in_usd, other_fee_in_usd_sign, tefra_wh_amount_in_usd, tefra_wh_amount_in_usd_sign, pershing_charge_in_usd, pershing_charge_in_usd_sign, brokerage_charge_in_usd, brokerage_charge_in_usd_sign, sales_credit_in_usd, sales_credit_in_usd_sign, settlement_fee_in_usd, settlement_fee_in_usd_sign, service_charge_in_usd, service_charge_in_usd_sign, markup_markdown_amount_in_usd, markup_markdown_amount_in_usd_sign, campo_71, dividend_payable_date, campo_73, dividend_record_date, dividend_type, campo_76, shares_of_record_quantity_for_dividends, order_size_quantity, campo_79, pool_factor, parsed_customer_account_number, ibd_number, security_type_code, security_modifier_code, security_calculation_code, minor_product_code, foreign_product_indicator, with_due_bill_indicator, taxable_municipal_bond_indicator, omnibus_indicator, external_order_id, campo_92, market_value_of_transaction, ip_number_parsed, reported_price, reported_price_sign, previous_day_market_value_of_transaction, price_in_usd, option_root_id, expiration_date, put_call_code, strike_price, repo_identifier, taxable, qualified, expanded_ip_number, expanded_exec_ip_number, expanded_legacy_ip_number, campo_109, campo_110, campo_111, eor)
    SELECT id_proceso, process_date, transaction_code, record_indicator_value, record_id_sequence_number, account_number, cusip_number, campo_6, underlying_cusip, campo_8, security_symbol, investment_professional_of_record, executing_investment_professional, transaction_type, buy_sell_code, open_close_indicator, par_key_code, source_code, maxx_key_code, process_date_sfl, trade_date, settlement_entry_date, campo_21, source_of_input, reference_number, batch_code, same_day_settlement, contra_account, market_code, blotter_code, cancel_code, correction_code, merket_limit_indicator, legend_code_1, legend_code_2, campo_34, quantity, quantity_sign, price_in_trade_currency, campo_38, price_in_trade_currency_sign, currency_indicator_for_price, net_amount_in_usd, net_amount_in_usd_sign, principal_in_usd, principal_in_usd_sign, interest_in_usd, interest_in_usd_sign, commision_in_usd, commision_in_usd_sign, tax_in_usd, tax_in_usd_sign, transaction_fee_in_usd, transaction_fee_in_usd_sign, misc_fee_in_usd, misc_fee_in_usd_sign, other_fee_in_usd, other_fee_in_usd_sign, tefra_wh_amount_in_usd, tefra_wh_amount_in_usd_sign, pershing_charge_in_usd, pershing_charge_in_usd_sign, brokerage_charge_in_usd, brokerage_charge_in_usd_sign, sales_credit_in_usd, sales_credit_in_usd_sign, settlement_fee_in_usd, settlement_fee_in_usd_sign, service_charge_in_usd, service_charge_in_usd_sign, markup_markdown_amount_in_usd, markup_markdown_amount_in_usd_sign, campo_71, dividend_payable_date, campo_73, dividend_record_date, dividend_type, campo_76, shares_of_record_quantity_for_dividends, order_size_quantity, campo_79, pool_factor, parsed_customer_account_number, ibd_number, security_type_code, security_modifier_code, security_calculation_code, minor_product_code, foreign_product_indicator, with_due_bill_indicator, taxable_municipal_bond_indicator, omnibus_indicator, external_order_id, campo_92, market_value_of_transaction, ip_number_parsed, reported_price, reported_price_sign, previous_day_market_value_of_transaction, price_in_usd, option_root_id, expiration_date, put_call_code, strike_price, repo_identifier, taxable, qualified, expanded_ip_number, expanded_exec_ip_number, expanded_legacy_ip_number, campo_109, campo_110, campo_111, eor
    FROM stage_pershing.fn_parse_gact_reg_a(_id_proceso);

    INSERT INTO stage_pershing.stage_gact_reg_b (id_proceso, process_date, transaction_code, record_indicator_value, record_id_sequence_number, account_number, security_currency_of_issuance, trade_currency_code, settlement_currency_code, settlement_usd_currency_fx_rate, settlement_usd_multiply_divide_code, cross_currency_fx_rate, currency_multiply_divide_code, accrued_interest_in_settlement_currency, accrued_interest_in_settlement_currency_sign, market_code, internal_reference_for_gloss, ibd_version, net_amount_in_settlement_currency, net_amount_in_settlement_currency_sign, principal_amount_in_settlement_currency, principal_amount_in_settlement_currency_sign, interest_in_settlement_currency, interest_in_settlement_currency_sign, commission_in_settlement_currency, commission_in_settlement_currency_sign, tax_in_settlement_currency, tax_in_settlement_currency_sign, transaction_fee_in_settlement_currency, transaction_fee_in_settlement_currency_sign, miscellaneous_fee_in_settlement_currency, miscellaneous_fee_in_settlement_currency_sign, other_fee_in_settlement_currency, other_fee_in_settlement_currency_sign, sales_credit_in_settlement_currency, sales_credit_in_settlement_currency_sign, settlement_fee_in_settlement_currency, settlement_fee_in_settlement_currency_sign, service_charge_in_settlement_currency, service_charge_in_settlement_currency_sign, markup_markdown_in_settlement_currency, markup_markdown_in_settlement_currency_sign, global_exchange, number_of_description_lines, last_description_line, description_line_1, description_line_2, description_line_3, description_line_4, description_line_5, description_line_6, description_line_7, description_line_8, description_line_9, description_line_10, description_line_11, description_line_12, security_currency_indicator, market_mnemonic_code, ccy_of_issuance_usd_ccy_fx_rate, ccy_of_issuance_usd_multiply_divide_code, alternate_security_id_type, alternate_security_id, alternate_security_id_type_2, alternate_security_id_2, international_non_dollar_symbol, confirmation_code_1, confirmation_code_2, confirmation_code_3, confirmation_code_4, pmp, total_amount_mark_up_down, total_amount_mark_up_down_sign, pmp_percent, campo_73, eor)
    SELECT id_proceso, process_date, transaction_code, record_indicator_value, record_id_sequence_number, account_number, security_currency_of_issuance, trade_currency_code, settlement_currency_code, settlement_usd_currency_fx_rate, settlement_usd_multiply_divide_code, cross_currency_fx_rate, currency_multiply_divide_code, accrued_interest_in_settlement_currency, accrued_interest_in_settlement_currency_sign, market_code, internal_reference_for_gloss, ibd_version, net_amount_in_settlement_currency, net_amount_in_settlement_currency_sign, principal_amount_in_settlement_currency, principal_amount_in_settlement_currency_sign, interest_in_settlement_currency, interest_in_settlement_currency_sign, commission_in_settlement_currency, commission_in_settlement_currency_sign, tax_in_settlement_currency, tax_in_settlement_currency_sign, transaction_fee_in_settlement_currency, transaction_fee_in_settlement_currency_sign, miscellaneous_fee_in_settlement_currency, miscellaneous_fee_in_settlement_currency_sign, other_fee_in_settlement_currency, other_fee_in_settlement_currency_sign, sales_credit_in_settlement_currency, sales_credit_in_settlement_currency_sign, settlement_fee_in_settlement_currency, settlement_fee_in_settlement_currency_sign, service_charge_in_settlement_currency, service_charge_in_settlement_currency_sign, markup_markdown_in_settlement_currency, markup_markdown_in_settlement_currency_sign, global_exchange, number_of_description_lines, last_description_line, description_line_1, description_line_2, description_line_3, description_line_4, description_line_5, description_line_6, description_line_7, description_line_8, description_line_9, description_line_10, description_line_11, description_line_12, security_currency_indicator, market_mnemonic_code, ccy_of_issuance_usd_ccy_fx_rate, ccy_of_issuance_usd_multiply_divide_code, alternate_security_id_type, alternate_security_id, alternate_security_id_type_2, alternate_security_id_2, international_non_dollar_symbol, confirmation_code_1, confirmation_code_2, confirmation_code_3, confirmation_code_4, pmp, total_amount_mark_up_down, total_amount_mark_up_down_sign, pmp_percent, campo_73, eor
    FROM stage_pershing.fn_parse_gact_reg_b(_id_proceso);

    INSERT INTO stage_pershing.stage_gact_reg_trailer (id_proceso, process_date, eof, campo_2, campo_3, date_of_data, campo_5, remote_id, campo_7, campo_8, number_detail_of_records, campo_10, eor)
    SELECT id_proceso, process_date, eof, campo_2, campo_3, date_of_data, campo_5, remote_id, campo_7, campo_8, number_detail_of_records, campo_10, eor
    FROM stage_pershing.fn_parse_gact_reg_trailer(_id_proceso);

end;
$$;

alter procedure stage_pershing.pa_parse_gact(bigint) owner to postgres;

